---
title: "FBS analyses"
output:
  word_document:
    toc: yes
    keep_md: yes
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_chunk$set(cache = TRUE, cache.path = "cache/", cache.trigger = 3, message = FALSE, warning = FALSE, dpi = 300, fig.retina = 2, fig.width = 8)
source(here::here("src/common_basis.R"))

years <- tibble(year = 1600:1700) %>%
  copy_to_a(con)
```

# RQ1

## Absolute output

```{r,fig.height=8}
years %>%
  transmute(m = year, b = year - 5, e = year + 5) %>%
  left_join(fbs_metadata_a %>%
    count(year = Estimated_admission_year), join_by(b <= year, e >= year)) %>%
  group_by(m) %>%
  summarise(mn = mean(n), .groups = "drop") %>%
  transmute(year = m, n = mn, set = "Member inductments 10 year rolling mean") %>%
  union_all(years %>% left_join(fbs_metadata_a %>%
    count(year = Estimated_admission_year) %>%
    mutate(set = "Member inductments"))) %>%
  union_all(years %>% inner_join(fbs_metadata_a, join_by(year >= Estimated_admission_year, year <= Estimated_DOD)) %>%
    count(year) %>%
    mutate(set = "Active members")) %>%
  union_all(years %>% left_join(fbs_records_a %>%
    inner_join(vd17_id_a, join_by(vd17_id)) %>%
    inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
    count(year = normalized_year, set))) %>%
  union_all(years %>% left_join(vd17_normalized_years_a %>%
    count(year = normalized_year) %>%
    mutate(set = "VD17"))) %>%
  mutate(graph = case_when(
    str_detect(set, "^Member inductments") ~ "Member inductments",
    set == "Active members" ~ "Active members",
    set == "VD17" ~ "VD17",
    str_detect(set, "^Active") ~ "Active member publications",
    T ~ "Member publications"
  )) %>%
  filter(year > 1600, year < 1700) %>%
  arrange(desc(set)) %>%
  collect() %>%
  mutate(graph = fct_relevel(graph, "VD17", "Active member publications", "Member publications", "Active members", "Member inductments")) %>%
  ggplot(aes(x = year, y = n, color = set)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  theme(legend.justification = c(1, 0), legend.position = c(0.98, -0.06), legend.background = element_blank(), legend.box.just = "bottom", legend.key = element_blank(), legend.box = "horizontal") +
  facet_wrap(~graph, scales = "free_y", ncol = 2)
```

```{r,fig.height=5}
years %>%
  left_join(fbs_metadata_a, join_by(year >= Estimated_admission_year, year <= Estimated_DOD)) %>%
  count(year, name = "members") %>%
  replace_na(list(members = 0)) %>%
  inner_join(years %>% left_join(fbs_records_a %>%
    filter(str_detect(set, "^Active")) %>%
    inner_join(vd17_id_a, join_by(vd17_id)) %>%
    inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
    count(year = normalized_year, set))) %>%
  filter(year > 1600, year < 1700) %>%
  ggplot(aes(x = year, y = n / members, color = set)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  theme(legend.position = "bottom")
```

```{r,fig.height=5}
years %>%
  left_join(fbs_metadata_a %>% inner_join(fbs_links_of_interest_a %>% distinct(member_number)), join_by(year >= Estimated_admission_year, year <= Estimated_DOD)) %>%
  count(year, name = "members") %>%
  replace_na(list(members = 0)) %>%
  inner_join(years %>% left_join(fbs_records_a %>%
    filter(str_detect(set, "^Active")) %>%
    inner_join(vd17_id_a, join_by(vd17_id)) %>%
    inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
    count(year = normalized_year, set))) %>%
  filter(year > 1600, year < 1700) %>%
  ggplot(aes(x = year, y = n / members, color = set)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  theme(legend.position = "bottom")
```

```{r}
years %>%
  left_join(fbs_metadata_a %>% inner_join(fbs_links_of_interest_a %>% distinct(member_number)), join_by(year >= Estimated_admission_year, year <= Estimated_DOD)) %>%
  count(year) %>%
  mutate(set = "Active members associated with publishing") %>%
  union_all(
    years %>% left_join(fbs_metadata_a, join_by(year >= Estimated_admission_year, year <= Estimated_DOD)) %>%
      count(year) %>%
      mutate(set = "Active members")
  ) %>%
  filter(year > 1600, year < 1700) %>%
  ggplot(aes(x = year, y = n, color = set)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  theme(legend.position = "bottom")
```


```{r,fig.height=5}
years %>%
  left_join(fbs_metadata_a, join_by(year >= Estimated_admission_year, year <= Estimated_DOD)) %>%
  count(year) %>%
  mutate(set = "Active members") %>%
  union_all(years %>% left_join(fbs_records_a %>%
    filter(str_detect(set, "^Active")) %>%
    inner_join(vd17_id_a, join_by(vd17_id)) %>%
    inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
    count(year = normalized_year, set))) %>%
  filter(year > 1600, year < 1700) %>%
  ggplot(aes(x = year, y = n, color = set)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  theme(legend.position = "bottom")
```

```{r}
fbs_records_a %>%
  filter(str_detect(set, "^Active")) %>%
  inner_join(vd17_id_a, join_by(vd17_id)) %>%
  inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
  left_join(vd17_genres_a, join_by(record_number)) %>%
  left_join(vd17_genre_categorisation_a) %>%
  count(year = normalized_year, group_1, set) %>%
  ggplot(aes(x = year, y = n, color = group_1)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  theme(legend.position = "bottom") +
  facet_wrap(~set)
```

```{r}
years %>%
  transmute(m = year, b = year - 2, e = year + 2) %>%
  inner_join(
    fbs_records_a %>%
      filter(set == "Active member substantive role and society purpose related") %>%
      inner_join(vd17_id_a, join_by(vd17_id)) %>%
      inner_join(vd17_genres_a, join_by(record_number)) %>%
      inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
      left_join(vd17_genre_categorisation_a) %>%
      count(year = normalized_year, group_1, group_3, set) %>%
      filter(group_1 == "Society-related"), join_by(b <= year, e >= year)
  ) %>%
  group_by(m, group_3) %>%
  summarise(mn = mean(n), .groups = "drop") %>%
  collect() %>%
  mutate(group_3 = fct_lump_n(group_3, n = 8, w = mn)) %>%
  ggplot(aes(x = m, y = mn, color = group_3)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete()
```

# RQ2

## Original language of society-linked translations

```{r}
vd17_normalized_langs_a %>%
  filter(!is.na(original_language)) %>%
  inner_join(fbs_records_a %>% inner_join(vd17_id_a)) %>%
  count(original_language, set) %>%
  arrange(set, desc(n)) %>%
  ggplot(aes(x = original_language, y = n)) +
  geom_col() +
  theme_hsci_discrete() +
  coord_flip() +
  facet_wrap(~set)
#  gt(rowname_col="original_language", groupname_col = "set") %>%
#  fmt_integer(n)
```

```{r, fig.height=11,fig.width=8}
vd17_normalized_langs_a %>%
  filter(!is.na(original_language)) %>%
  inner_join(fbs_records_a %>% inner_join(vd17_id_a)) %>%
  left_join(vd17_genres_a %>% inner_join(vd17_genre_categorisation_a), join_by(record_number)) %>%
  count(group_3, set) %>%
  arrange(set, desc(n)) %>%
  ggplot(aes(x = group_3, y = n)) +
  geom_col() +
  theme_hsci_discrete() +
  coord_flip() +
  facet_wrap(~set, scales = "free_x")
#  gt(rowname_col="original_language", groupname_col = "set") %>%
#  fmt_integer(n)
```

# RQ 3

```{r}
rda_printers <- vd17_a %>%
  filter(field_code == "029F", subfield_code == "4", value == "prt") %>%
  select(record_number, field_number) %>%
  inner_join(vd17_a %>% filter(subfield_code == "7"), join_by(record_number, field_number)) %>%
  select(record_number, printer_gnd = value)

printers <- vd17_a %>%
  filter(field_code == "033J", subfield_code == "7") %>%
  select(record_number, printer_gnd = value)

additional_printers <- vd17_a %>%
  filter(field_code == "028C", (subfield_code == "4" & value == "prt") | (subfield_code == "B" & str_detect(value, "^Drucker|^Verleger"))) %>%
  distinct(record_number, field_number) %>%
  inner_join(vd17_a %>% filter(subfield_code == "7"), join_by(record_number, field_number)) %>%
  select(record_number, printer_gnd = value)

all_printers <- rda_printers %>%
  union_all(printers) %>%
  union_all(additional_printers) %>%
  distinct(record_number, printer_gnd)

fbs_records_a %>%
  filter(set == "Active member substantive role") %>%
  inner_join(vd17_id_a) %>%
  left_join(all_printers %>% inner_join(vd17_auth_id_a %>% inner_join(vd17_auth_name_a), join_by(printer_gnd == GND))) %>%
  count(unified_name, set) %>%
  arrange(set, desc(n)) %>%
  collect() %>%
  mutate(unified_name = fct_lump_n(unified_name, n = 30, w = n)) %>%
  filter(!is.na(unified_name), unified_name != "Other") %>%
  ggplot(aes(x = unified_name, y = n)) +
  geom_col() +
  theme_hsci_discrete() +
  coord_flip() +
  facet_wrap(~set, scales = "free_x")
```

```{r}
places_of_publication <- vd17_normalized_locations_a %>%
  filter(location_type == "pup") %>%
  select(record_number, place_of_publication = location)
places_of_production <- vd17_normalized_locations_a %>%
  filter(location_type == "mfp") %>%
  select(record_number, place_of_production = location)
places_of_distribution <- vd17_normalized_locations_a %>%
  filter(location_type == "dbp") %>%
  select(record_number, place_of_distribution = location)

unified_places_of_publication <- vd17_a %>%
  distinct(record_number) %>%
  left_join(places_of_publication, join_by(record_number)) %>%
  left_join(places_of_production, join_by(record_number)) %>%
  left_join(places_of_distribution, join_by(record_number)) %>%
  mutate(place_of_publication = coalesce(place_of_publication, place_of_production, place_of_distribution)) %>%
  filter(!is.na(place_of_publication)) %>%
  mutate(place_of_publication = str_replace_all(str_to_lower(place_of_publication), "[^a-zß]", "")) %>%
  distinct(record_number, place_of_publication)

years %>%
  transmute(m = year, b = year - 5, e = year + 5) %>%
  left_join(
    fbs_records_a %>%
      filter(set == "Active member substantive role") %>%
      inner_join(vd17_id_a) %>%
      left_join(unified_places_of_publication) %>%
      left_join(vd17_normalized_years_a) %>%
      count(normalized_year, place_of_publication, set),
    join_by(b <= normalized_year, e >= normalized_year)
  ) %>%
  replace_na(list(n = 0)) %>%
  #  complete(m,set,place_of_publication,fill=list(n=0)) %>%
  group_by(m, place_of_publication) %>%
  summarise(n = sum(n), .groups = "drop") %>%
  collect() %>%
  mutate(place_of_publication = fct_lump_n(place_of_publication, n = 10, w = n)) %>%
  ggplot(aes(x = m, y = n, color = place_of_publication)) +
  geom_point() +
  theme_hsci_discrete()
```

```{r}
fbs_records_a %>%
  filter(set == "Member substantive role and society purpose related") %>%
  inner_join(vd17_id_a) %>%
  left_join(vd17_normalized_locations_a %>% filter(location_type == "pup")) %>%
  left_join(vd17_genres_a %>% left_join(vd17_genre_categorisation_a %>% mutate(group_4 = coalesce(group_4, group_3))), join_by(record_number)) %>%
  left_join(vd17_normalized_years_a, join_by(record_number)) %>%
  filter(normalized_year >= 1600, normalized_year < 1700) %>%
  count(normalized_year, location, group_3) %>%
  collect() %>%
  mutate(group_3 = fct_lump_n(group_3, n = 2, w = n)) %>%
  mutate(location = fct_lump_n(location, n = 4, w = n)) %>%
  group_by(normalized_year, location, group_3) %>%
  ggplot(aes(x = normalized_year, y = n, color = group_3, fill = group_3)) +
  geom_smooth() +
  geom_point(size = 0.5) +
  facet_wrap(~location, scales = "free_y") +
  theme_hsci_discrete()
```


```{r}
fbs_records_a %>%
  filter(set == "Member substantive role and society purpose related") %>%
  inner_join(vd17_id_a) %>%
  left_join(vd17_normalized_locations_a %>% filter(location_type == "pup")) %>%
  left_join(vd17_genres_a %>% left_join(vd17_genre_categorisation_a %>% mutate(group_4 = coalesce(group_4, group_3))), join_by(record_number)) %>%
  left_join(vd17_normalized_years_a, join_by(record_number)) %>%
  filter(normalized_year >= 1600, normalized_year < 1700) %>%
  count(normalized_year, location, group_2) %>%
  collect() %>%
  mutate(location = fct_lump_n(location, n = 10, w = n)) %>%
  ggplot(aes(x = normalized_year, y = n, color = group_2, fill = group_2)) +
  geom_smooth() +
  geom_point(size = 0.5) +
  theme_hsci_discrete() +
  facet_wrap(~location, scales = "free_y")
```


# RQ4

```{r,fig.height=11,fig.width=8}
fbs_records_a %>%
  filter(set == "Member substantive role and society purpose related") %>%
  inner_join(vd17_id_a) %>%
  inner_join(vd17_person_links_a %>%
    filter(role == "dte"), join_by(record_number)) %>%
  count(combined_name, set) %>%
  arrange(set, desc(n)) %>%
  collect() %>%
  group_by(set) %>%
  mutate(combined_name = fct_reorder(fct_lump_n(combined_name, n = 30, w = n), n)) %>%
  ungroup() %>%
  filter(combined_name != "Other") %>%
  ggplot(aes(x = combined_name, y = n)) +
  geom_col() +
  theme_hsci_discrete() +
  coord_flip() +
  facet_wrap(~set, scales = "free", ncol = 1)
```

```{r, eval=FALSE}
fbs_records_a %>%
  filter(set == "Member substantive role and society purpose related") %>%
  inner_join(vd17_id_a) %>%
  inner_join(vd17_person_links_a %>%
    filter(role == "dte"), join_by(record_number)) %>%
  select(vd17_id, dedicatee = combined_name) %>%
  add_metadata_fields() %>%
  collect() %>%
  prepare_for_gsheets() %>%
  relocate(dedicatee) %>%
  arrange(dedicatee, vd17_id) %>%
  sheet_write(ss = "1ZpDUDTvX0x964N4wks3QvYIspRIxTZndPNIqA_-psgY", sheet = "Society purpose related dedications")
```



# Misc

```{r}
fbs_metadata_a %>%
  mutate(active_time = as.integer(Estimated_DOD) - as.integer(Estimated_admission_year)) %>%
  filter(active_time >= 0) %>%
  ggplot(aes(x = 1, y = active_time)) +
  geom_quasirandom() +
  theme_hsci_discrete()
```

```{r}
fbs_links_of_interest_a %>%
  left_join(vd17_normalized_years_a, join_by(record_number)) %>%
  group_by(member_number) %>%
  summarise(earliest_year = min(normalized_year), latest_year = max(normalized_year)) %>%
  mutate(active_time = latest_year - earliest_year) %>%
  ggplot(aes(x = 1, y = active_time)) +
  geom_quasirandom() +
  theme_hsci_discrete()
```

```{r}
members_through_time <- seq(20, 60, by = 10) %>%
  map(~ years %>%
    inner_join(fbs_metadata_a %>% mutate(Estimated_admission_year = as.integer(Estimated_admission_year), latest_year = as.integer(Estimated_admission_year) + .x), join_by(year >= Estimated_admission_year, year <= latest_year)) %>%
    count(year) %>%
    mutate(set = .x)) %>%
  reduce(union_all)
members_through_time %>%
  ggplot(aes(x = year, y = n, color = as.character(set))) +
  geom_point() +
  theme_hsci_discrete()
```

```{r}
fbs_records_a %>%
  inner_join(vd17_id_a, join_by(vd17_id)) %>%
  inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
  count(normalized_year, set) %>%
  inner_join(members_through_time %>% rename(normalized_year = year, members = n, memberset = set)) %>%
  filter(normalized_year > 1630, normalized_year < 1680) %>%
  ggplot(aes(x = normalized_year, y = n / members, color = set)) +
  geom_point(size = 0.5) +
  scale_x_continuous(breaks = seq(1600, 1700, by = 10)) +
  theme_hsci_discrete() +
  facet_wrap(~memberset) +
  theme(legend.position = "bottom")
```


```{r, eval=FALSE}
library(googledrive)
drive_put(here("src/jiemakel/fbs_analyses.docx"), path = as_id("161toNA4jUgTzMjndSDVp1kpL9yGfHkwG"), name = "fbs_analyses", type = "application/vnd.google-apps.document")
```
