---
title: "FBS analysis"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = here::here())
library(here)
source(here("code/common_basis.R"), local = knitr::knit_global())
library(tidyverse)
library(gghsci)
library(gt)
p <- function(number) {
  return(format(number, scientific = FALSE, big.mark = ","))
}
pp <- function(percentage, accuracy = 0.01) {
  return(scales::percent(percentage, accuracy = accuracy))
}
```


```{r}
all_match <- read.csv(here("all_match.csv"))
all_match <- select (all_match, -c('X','full_name_vd17','normalized_year','field_number'))
all_match_subset <-  all_match%>%
  filter(
    field_code %in% c("028A", "028B", "028C"), # FBS GND has to appear in one of these fields
    is.na(role) | !role %in% c("ctb", "dte"), # normed role has to be unknown or not one of these
    is.na(role) | !(role == "oth" & field_code == "028C" & !is.na(role2) & str_detect(role2, "^Beiträger|^Mitwirkender")), # in field 028C, if role is other, role2 should not be one of these
    is.na(role2) | !str_detect(role2, !!!str_flatten(c(
      "^AdressatIn",
      "ErwähnteR",
      "GefeierteR",
      "Mitglied eines Ausschusses, der akademische Grade vergibt",
      "Normerlassende Gebietskörperschaft",
      "Praeses",
      "RespondentIn",
      "Sonstige Person, Familie und Körperschaft",
      "VerfasserIn eines Vorworts",
      "VerfasserIn von ergänzendem Text",
      "VerfasserIn von Zusatztexten",
      "VertragspartnerIn",
      "WidmendeR",
      "WidmungsempfängerIn",
      "ZensorIn"
    ), collapse = "|^"))
  )
```


# Joining vd17_id with fbs_links_of_interest 
```{r}
fbs_links_of_interest_local <- fbs_links_of_interest_a %>%
  inner_join(fbs_metadata_a %>% select(GND,Member_number_new,First_name_new,Last_name_new,Society_name,DOB,DOD) %>% mutate(GND = str_c("gnd/", GND))) %>%
  inner_join(vd17_id_a) %>%
  mutate(member_number=Member_number_new,first_name=First_name_new,last_name=Last_name_new)%>%
  collect() %>%
  select(where(~!all(is.na(.x))))

fbs_links_of_interest_local <- select (fbs_links_of_interest_local, c('record_number','vd17_id','member_number','first_name', 'last_name','role','role2','field_code'))

```

```{r}
fbs_links_of_interest_matches <- rbind(fbs_links_of_interest_local,all_match_subset)

fbs_links_of_interest_matches <- fbs_links_of_interest_matches %>%
  distinct()
```

# Creating local tables of vd17 normalized years, genres, languages, id and title.
```{r}
vd17_normalized_years_local <- vd17_normalized_years_a %>%
  collect()

genre_list2 <- c("Educational","Schul- und Hochschulschriften","Hochschulschrift","Dissertation","Dissertationensammlung","Matrikel","Universitätsprogramm","Vorlesung","Rede","Vorlesungsverzeichnis","Jugendsachbuch","Jugendbuch","Schulbuch","Rechenbuch","Mathematik","Grammatik","Wörterbuch","Fibel","Lesebuch","Anthologie","Schulprogramm","Judicial","Legal","Entscheidungssammlung","Fallsammlung","Konsiliensammlung","Konsilium","Satzung","Governmental","Amtsdruckschrift","Edikt","Gesetz","Mandat","Verordnung","Gesetzesammlung","Kapitulation","Privileg","Richtlinie","Regelsammlung","Vertrag","Religious","Theological","Agende","Rituale","Beichtspiegel","Bibel","Brevier","Gebet","Katechismus","Missale","Psalter","Secretarial","Briefsteller","Formularsammlung","Schreibmeisterbuch","Musterbuch","Regesten","Urkundenbuch","Business","Mercantile","Anzeige","Subskriptionsanzeige","Bücheranzeige","Meßrelation","Subskribentenliste","Verkaufskatalog","Katalog","Antiquariatskatalog","Auktionskatalog","Buchhandelskatalog","Meßkatalog","Festungsbau","Kriegskunde","Bericht","Reisebericht","Brief","Briefsammlung","Regelsammlung","Statistik","Streitschrift","Einblattdruck","Flugschrift","Kolportageliteratur","Satire")

vd17_genres_local <- vd17_genres_a %>%
  collect()%>%
  filter(!genre %in% c(genre_list2))

vd17_normalized_langs_local <- vd17_normalized_langs_a %>%
  collect()

vd17_id_local <- vd17_id_a %>%
  collect()

vd17_titles_local <- vd17_titles_a %>%
  collect()
```


```{r}
genre_list1_a <- c("Lyrik","Poetry","Ballade","Elegie","Epigramm","Epikedeion","Figurengedicht","Gesangbuch","Kirchenlied","Lied","Liedersammlung","Anthologie")
genre_list1_b <- c("Drama","Theatre","Fastnachtspiel","Komödie","Märtyrerdrama","Schauspiel","Schwank","Theaterzettel","Einblattdruck","Perioche","Tragödie")
genre_list1_c <- c("Epik","Prose","Anekdote","Autobiographie","Tagebuch","Biographie","Heiligenvita","Epos","Erzählung","Erzählsammlung","Fabel","Märchen","Novelle","Reisebericht","Erlebnisbericht","Roman","Sage","Satire","Streitschrift","Verserzählung")
genre_list1_d <- c("Lesebuch","Emblembuch","Erotische Literatur","Kommentar","Libretto","Schäferdichtung")
genre_list1_e <- c("Grammatik","Schulbuch","Sprachführer","Konkordanz","Wörterbuch","Lexikon","Enzyklopädie","Wörterbuch","Poetik","Rhetorik")
genre_list1_f <- c("Aphorismus","Sprichwortsammlung","Zitatensammlung","Anstandsliteratur","Tischzucht","Komplimentierbuch","Briefsteller","Frauenliteratur","Fürstenspiegel","Hausväterliteratur","Ratgeber","Jugendbuch","Jugendsachbuch","Moralische Wochenschrift","Zeitschrift","Spiel","Sprichwortsammlung","Aphorismus","Zitatensammlung")
genre_list1_g <- c("Gelegenheitsschrift","Festbeschreibung","Gesellschaftschrift","Preisschrift","Rezensionszeitschrift","Gesellschaftsschrift","Funeral Sermons","Leichenpredigt","Leichenpredigtsammlung")
```


```{r}
genre_list3_a <- c("Archäologie","Altertumskunde","Chronik","Erlebnisbericht","Autobiographie","Reisebericht","Genealogie","Tagebuch","Wappenbuch")
genre_list3_b <- c("Botanik","Pflanzenbuch","Gartenbau","Jagdliteratur","Landwirtschaft","Praktik","Kalender","Tierbuch","Zoologie")
genre_list3_c <- c("Atlas","Bergbau","Geographie","Topographie","Geologie","Itinerar","Karte","Plan","Ortsverzeichnis","Mineralogie","Reiseführer","Führer")
genre_list3_d <- c("Alchemie","Chemie","Astronomie","Astrologie","Physik","Akustik","Magnetismus","Mechanik","Optik","Geometrie","Mathematik","Rechenbuch")
genre_list3_e <- c("Anatomie","Arzneibuch","Pharmakopöe","Chiromantie","Chirurgie","Gynäkologie","Medizin","Seuchenschrift","Physiognomie","Tiermedizin")
genre_list3_f <- c("Musikbuch","Musiknoten")
genre_list3_g <- c("Architektur","Ornamentstich")
genre_list3_h <- c("Festbeschreibung","Gelegenheitsschrift","Leichenpredigt","Rede","Vorlesung","Panegyrikos","Sprachführer","Grammatik","Wörterbuch")
genre_list3_i <- c("Pädagogik")
genre_list3_j <- c("Kochbuch")
genre_list3_k <- c("Ars moriendi","Erbauungsliteratur","Freimaurerliteratur","Gebetbuch","Heiligenvita","Biographie","Jesuitendrama","Jesuiten","Perioche","Ordensliteratur","Judaicum","Legende","Ordensliteratur","Perioche","Theaterzettel","Predigtsammlung","Totentanz")
genre_list3_l <- c("Adressbuch","Almanach","Kalender","Anleitung","Ratgeber","Bibliographie","Bücheranzeige","Buchbinderanweisung","Subskriptionsanzeige","Einführung","Handbuch","Enzyklopädie","Lexikon","Führer","Ratgeber","Praktik","Volksschrifttum","Katalog","Verkaufskatalog","Bibliothekskatalog","Kommentar","Konkordanz","Musterbuch","Schreibmeisterbuch","Ornamentstich","Ratgeber","Anleitung","Briefsteller","Hausväterliteratur","Porträtwerk","Preisschrift","Akademieschrift","Regelsammlung","Rezension","Rezensionszeitschrift","Zeitschrift","Akademieschrift","Traktat","Trivialliteratur","Kolportageliteratur")
genre_list3_m <- c("Einblattdruck","Flugschrift","Streitschrift","Volksschrifttum","Volksbuch","Theaterzettel","Flugblatt","Tabelle","Zeitung","Zeitschrift")
```


```{r}
fbs_dedicatees_cat1 <- fbs_links_of_interest_matches %>%
  filter(field_code=="028C",role2=="Widmungsempfänger")%>%
  left_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  inner_join(vd17_titles_local %>% select(record_number,title))%>%
  left_join(vd17_genres_local, by = c("record_number"))%>%
  select (record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,genre)%>%
   mutate(genre_category = case_when(
    genre %in% genre_list1_a ~ "Lyrik/Poetry",
    genre %in% genre_list1_b ~ "Drama/Theatre",
    genre %in% genre_list1_c ~ "Epik/Prose",
    genre %in% genre_list1_d ~ "Other Literature Related",
    genre %in% genre_list1_e ~ "Linguistic and Language",
    genre %in% genre_list1_f ~ "Virtue, Civility and Ethics",
    genre %in% genre_list1_g ~ "Other Society Related"
  ))%>%
  na.omit(genre_category)

genres_dedicatees_fbs_cat1 <- fbs_dedicatees_cat1%>%
  na.omit(fbs_translation_cat1$genre_category)%>%
  select(vd17_id,record_number,normalized_year,genre)%>%
  distinct(vd17_id,record_number,normalized_year,genre)%>%
  group_by(normalized_year) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(genre_category = case_when(
    genre %in% genre_list1_a ~ "Lyrik/Poetry",
    genre %in% genre_list1_b ~ "Drama/Theatre",
    genre %in% genre_list1_c ~ "Epik/Prose",
    genre %in% genre_list1_d ~ "Other Literature Related",
    genre %in% genre_list1_e ~ "Linguistic and Language",
    genre %in% genre_list1_f ~ "Virtue, Civility and Ethics",
    genre %in% genre_list1_g ~ "Other Society Related"
  ))


genres_dedicatees_fbs_cat1%>%
  na.omit(genres_dedicatees_fbs_cat1$genre_category)%>%
  ggplot(aes(x=normalized_year,y=n,fill=genre_category))+
  geom_col(show.legend = FALSE)+
  facet_wrap(~genre_category, scales="free_y")+
  xlab("Year") + ylab("Dedicatees_FBS-Genre_category1")+
  scale_x_continuous(breaks = seq(1000, 2000, by = 5))+
  theme_hsci_discrete()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

genres_members_dedicatees_cat1 <- fbs_dedicatees_cat1%>%
  na.omit(fbs_translation_cat1$genre_category)%>%
  select(vd17_id,record_number,normalized_year,member_number,genre)%>%
  distinct(vd17_id,record_number,normalized_year,member_number,genre)%>%
  group_by(normalized_year,member_number) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(genre_category = case_when(
    genre %in% genre_list1_a ~ "Lyrik/Poetry",
    genre %in% genre_list1_b ~ "Drama/Theatre",
    genre %in% genre_list1_c ~ "Epik/Prose",
    genre %in% genre_list1_d ~ "Other Literature Related",
    genre %in% genre_list1_e ~ "Linguistic and Language",
    genre %in% genre_list1_f ~ "Virtue, Civility and Ethics",
    genre %in% genre_list1_g ~ "Other Society Related"
  ))
```


```{r}
fbs_dedicatees_cat3 <- fbs_links_of_interest_matches %>%
  filter(field_code=="028C",role2=="Widmungsempfänger")%>%
  left_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  inner_join(vd17_titles_local %>% select(record_number,title))%>%
  left_join(vd17_genres_local, by = c("record_number"))%>%
  select (record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,genre)%>%
   mutate(genre_category = case_when(
    genre %in% genre_list3_a ~ "History, Archaeology and related",
    genre %in% genre_list3_b ~ "Botany, Zoology, Agriculture",
    genre %in% genre_list3_c ~ "Geography, Geology, Mineralogy, Mining",
    genre %in% genre_list3_d ~ "Mathematics, Natural Sciences, Astronomy",
    genre %in% genre_list3_e ~ "Medicine, Pharmacy",
    genre %in% genre_list3_f ~ "Music and related",
    genre %in% genre_list3_g ~ "Arts and related",
    genre %in% genre_list3_h ~ "Literature, language and related",
    genre %in% genre_list3_i ~ "Education",
    genre %in% genre_list3_j ~ "Manners and customs",
    genre %in% genre_list3_k ~ "Religion/Theology and related",
    genre %in% genre_list3_l ~ "General works",
    genre %in% genre_list3_m ~ "Formats"
  ))%>%
  na.omit(genre_category)

genres_dedicatees_fbs_cat3 <- fbs_dedicatees_cat3%>%
  na.omit(fbs_translation_cat3$genre_category)%>%
  select(vd17_id,record_number,normalized_year,genre)%>%
  distinct(vd17_id,record_number,normalized_year,genre)%>%
  group_by(normalized_year) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(genre_category = case_when(
    genre %in% genre_list3_a ~ "History, Archaeology and related",
    genre %in% genre_list3_b ~ "Botany, Zoology, Agriculture",
    genre %in% genre_list3_c ~ "Geography, Geology, Mineralogy, Mining",
    genre %in% genre_list3_d ~ "Mathematics, Natural Sciences, Astronomy",
    genre %in% genre_list3_e ~ "Medicine, Pharmacy",
    genre %in% genre_list3_f ~ "Music and related",
    genre %in% genre_list3_g ~ "Arts and related",
    genre %in% genre_list3_h ~ "Literature, language and related",
    genre %in% genre_list3_i ~ "Education",
    genre %in% genre_list3_j ~ "Manners and customs",
    genre %in% genre_list3_k ~ "Religion/Theology and related",
    genre %in% genre_list3_l ~ "General works",
    genre %in% genre_list3_m ~ "Formats"
  ))


genres_dedicatees_fbs_cat3%>%
  na.omit(genres_translations_fbs_cat3$genre_category)%>%
  ggplot(aes(x=normalized_year,y=n,fill=genre_category))+
  geom_col(show.legend = FALSE)+
  facet_wrap(~genre_category, scales="free_y")+
  xlab("Year") + ylab("Dedicatees_FBS-Genre_category3")+
  scale_x_continuous(breaks = seq(1000, 2000, by = 5))+
  theme_hsci_discrete()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

genres_members_dedicatees_cat3 <- fbs_dedicatees_cat3%>%
  na.omit(fbs_translation_cat3$genre_category)%>%
  select(vd17_id,record_number,normalized_year,member_number,genre)%>%
  distinct(vd17_id,record_number,normalized_year,member_number,genre)%>%
  group_by(normalized_year,member_number) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(genre_category = case_when(
    genre %in% genre_list3_a ~ "History, Archaeology and related",
    genre %in% genre_list3_b ~ "Botany, Zoology, Agriculture",
    genre %in% genre_list3_c ~ "Geography, Geology, Mineralogy, Mining",
    genre %in% genre_list3_d ~ "Mathematics, Natural Sciences, Astronomy",
    genre %in% genre_list3_e ~ "Medicine, Pharmacy",
    genre %in% genre_list3_f ~ "Music and related",
    genre %in% genre_list3_g ~ "Arts and related",
    genre %in% genre_list3_h ~ "Literature, language and related",
    genre %in% genre_list3_i ~ "Education",
    genre %in% genre_list3_j ~ "Manners and customs",
    genre %in% genre_list3_k ~ "Religion/Theology and related",
    genre %in% genre_list3_l ~ "General works",
    genre %in% genre_list3_m ~ "Formats"
  ))
```
```{r}
fbs_dedicatees_cat_1 <- gs4_create(
  "fbs_dedicatees_cat_1",
  sheets = fbs_dedicatees_cat1%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://kxp.k10plus.de/DB=1.28/CMD?ACT=SRCHA&IKT=8079&TRM=%27',vd17_id,'%27","',vd17_id,'")'))))
fbs_dedicatees_cat_1

genres_dedicatees_fbs_cat_1 <- gs4_create(
  "genres_dedicatees_fbs_cat1",
  sheets =genres_dedicatees_fbs_cat1)
genres_dedicatees_fbs_cat_1


genres_members_dedicatees_cat_1 <- gs4_create(
  "genres_members_dedicatees_cat1",
  sheets =genres_members_dedicatees_cat1)
genres_members_dedicatees_cat_1 
```


```{r}
fbs_dedicatees_cat_3 <- gs4_create(
  "fbs_dedicatees_cat_3",
  sheets = fbs_dedicatees_cat3%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://kxp.k10plus.de/DB=1.28/CMD?ACT=SRCHA&IKT=8079&TRM=%27',vd17_id,'%27","',vd17_id,'")'))))
fbs_dedicatees_cat_3

genres_dedicatees_fbs_cat_3 <- gs4_create(
  "genres_dedicatees_fbs_cat3",
  sheets =genres_dedicatees_fbs_cat3)
genres_dedicatees_fbs_cat_3


genres_members_dedicatees_cat_3 <- gs4_create(
  "genres_members_dedicatees_cat3",
  sheets =genres_members_dedicatees_cat3)
genres_members_dedicatees_cat_3 
```

