---
title: "FBS analysis"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = here::here())
library(here)
source(here("code/common_basis.R"), local = knitr::knit_global())
library(tidyverse)
library(gghsci)
library(gt)
p <- function(number) {
  return(format(number, scientific = FALSE, big.mark = ","))
}
pp <- function(percentage, accuracy = 0.01) {
  return(scales::percent(percentage, accuracy = accuracy))
}
```

```{r}
all_match <- read.csv(here("all_match.csv"))
all_match <- select (all_match, -c('X','full_name_vd17','normalized_year','field_number'))
all_match_subset <-  all_match%>%
  filter(
    field_code %in% c("028A", "028B", "028C"), # FBS GND has to appear in one of these fields
    is.na(role) | !role %in% c("ctb", "dte"), # normed role has to be unknown or not one of these
    is.na(role) | !(role == "oth" & field_code == "028C" & !is.na(role2) & str_detect(role2, "^Beiträger|^Mitwirkender")), # in field 028C, if role is other, role2 should not be one of these
    is.na(role2) | !str_detect(role2, !!!str_flatten(c(
      "^AdressatIn",
      "ErwähnteR",
      "GefeierteR",
      "Mitglied eines Ausschusses, der akademische Grade vergibt",
      "Normerlassende Gebietskörperschaft",
      "Praeses",
      "RespondentIn",
      "Sonstige Person, Familie und Körperschaft",
      "VerfasserIn eines Vorworts",
      "VerfasserIn von ergänzendem Text",
      "VerfasserIn von Zusatztexten",
      "VertragspartnerIn",
      "WidmendeR",
      "WidmungsempfängerIn",
      "ZensorIn"
    ), collapse = "|^"))
  )
```

```{r}
all_match_subset <- select(all_match_subset,-c('role'))
```


# Joining vd17_id and vd17_titles tables with fbs_links_of_interest 
```{r}
fbs_links_of_interest_local <- fbs_links_of_interest_a %>%
  inner_join(fbs_metadata_a %>% select(GND,Member_number_new,First_name_new,Last_name_new,Society_name,DOB,DOD) %>% mutate(GND = str_c("gnd/", GND))) %>%
  inner_join(vd17_id_a) %>%
  mutate(member_number=Member_number_new,first_name=First_name_new,last_name=Last_name_new)%>%
  collect() %>%
  select(where(~!all(is.na(.x))))

fbs_links_of_interest_local <- select (fbs_links_of_interest_local, c('record_number','vd17_id','member_number','first_name', 'last_name','role2','field_code'))

```

```{r}
fbs_links_of_interest_matches <- rbind(fbs_links_of_interest_local,all_match_subset)

fbs_links_of_interest_matches <- fbs_links_of_interest_matches %>%
  distinct()
```

# Creating local tables of vd17 normalized years, genres, languages and id.
```{r}
vd17_normalized_years_local <- vd17_normalized_years_a %>%
  collect()

vd17_genres_local <- vd17_genres_a %>%
  collect()%>%
  filter(!genre %in% c("Hochschulschrift","Dissertation","Dissertationensammlung","Matrikel","Universitätsprogramm","Vorlesung","Rede","Vorlesungsverzeichnis","Jugendsachbuch","Jugendbuch","Schulbuch","Rechenbuch","Mathematik","Grammatik","Wörterbuch","Fibel","Lesebuch","Anthologie","Schulprogramm","Amtsdruckschrift","Edikt","Gesetz","Mandat","Verordnung","Gesetzesammlung","Kapitulation","Privileg","Richtlinie","Regelsammlung","Vertrag","Entscheidungssammlung","Fallsammlung","Konsiliensammlung","Konsilium","Satzung","Agende","Rituale","Beichtspiegel","Bibel","Brevier","Gebet","Katechismus","Missale","Psalter","Secretarial","Briefsteller","Formularsammlung","Schreibmeisterbuch","Musterbuch","Regesten","Urkundenbuch","Anzeige","Subskriptionsanzeige","Bücheranzeige","Meßrelation","Subskribentenliste","Verkaufskatalog","Katalog","Antiquariatskatalog","Auktionskatalog","Buchhandelskatalog","Meßkatalog","Festungsbau","Kriegskunde","Bericht","Reisebericht","Brief","Briefsammlung","Regelsammlung","Statistik","Streitschrift","Einblattdruck","Flugschrift","Kolportageliteratur","Satire"))

vd17_normalized_langs_local <- vd17_normalized_langs_a %>%
  collect()

vd17_id_local <- vd17_id_a %>%
  collect()

vd17_titles_local <- vd17_titles_a %>%
  collect()
```

```{r}
genre_list1_1 <- c("Lyrik","Ballade","Elegie","Epigramm","Epikedeion","Figurengedicht","Gesangbuch","Kirchenlied","Lied","Liedersammlung","Anthologie","Drama","Fastnachtspiel","Komödie","Märtyrerdrama","Schauspiel","Schwank","Theaterzettel","Einblattdruck","Perioche","Tragödie","Epik","Anekdote","Autobiographie","Tagebuch","Biographie","Heiligenvita","Epos","Erzählung","Erzählsammlung","Fabel","Märchen","Novelle","Reisebericht","Erlebnisbericht","Roman","Sage","Satire","Streitschrift","Verserzählung","Lesebuch","Emblembuch","Erotische Literatur")
genre_list1_2 <- c("Kommentar","Libretto","Schäferdichtung","Grammatik","Schulbuch","Sprachführer","Konkordanz","Wörterbuch","Lexikon","Enzyklopädie","Wörterbuch","Poetik","Rhetorik","Aphorismus","Sprichwortsammlung","Zitatensammlung","Anstandsliteratur","Tischzucht","Komplimentierbuch","Briefsteller","Frauenliteratur","Fürstenspiegel","Hausväterliteratur","Ratgeber","Jugendbuch","Jugendsachbuch","Moralische Wochenschrift","Zeitschrift","Spiel","Sprichwortsammlung","Aphorismus","Zitatensammlung","Gelegenheitsschrift","Festbeschreibung","Gesellschaftschrift","Preisschrift","Rezensionszeitschrift","Gesellschaftsschrift","Funeral Sermons","Leichenpredigt","Leichenpredigtsammlung")

genre_list3_1 <- c("Archäologie","Altertumskunde","Chronik","Erlebnisbericht","Autobiographie","Reisebericht","Genealogie","Tagebuch","Wappenbuch","Botanik","Pflanzenbuch","Gartenbau","Jagdliteratur","Landwirtschaft","Praktik","Kalender","Tierbuch","Zoologie","Atlas","Bergbau","Geographie","Topographie","Geologie","Itinerar","Karte","Plan","Ortsverzeichnis","Mineralogie","Reiseführer","Führer","Alchemie","Chemie","Astronomie","Astrologie","Physik","Akustik","Magnetismus","Mechanik","Optik","Geometrie","Mathematik","Rechenbuch","Anatomie","Arzneibuch","Pharmakopöe","Chiromantie","Chirurgie","Gynäkologie","Medizin","Seuchenschrift","Physiognomie","Tiermedizin","Musikbuch","Musiknoten","Architektur","Ornamentstich","Festbeschreibung","Gelegenheitsschrift","Leichenpredigt","Rede","Vorlesung","Panegyrikos","Sprachführer","Grammatik","Wörterbuch","Pädagogik","Kochbuch")
genre_list3_2 <- c("Ars moriendi","Erbauungsliteratur","Freimaurerliteratur","Gebetbuch","Heiligenvita","Biographie","Jesuitendrama","Jesuiten","Perioche","Ordensliteratur","Judaicum","Legende","Ordensliteratur","Perioche","Theaterzettel","Predigtsammlung","Totentanz","Adressbuch","Almanach","Kalender","Anleitung","Ratgeber","Bibliographie","Bücheranzeige","Buchbinderanweisung","Subskriptionsanzeige","Einführung","Handbuch","Enzyklopädie","Lexikon","Führer","Ratgeber","Praktik","Volksschrifttum","Katalog","Verkaufskatalog","Bibliothekskatalog","Kommentar","Konkordanz","Musterbuch","Schreibmeisterbuch","Ornamentstich","Ratgeber","Anleitung","Briefsteller","Hausväterliteratur","Porträtwerk","Preisschrift","Akademieschrift","Regelsammlung","Rezension","Rezensionszeitschrift","Zeitschrift","Akademieschrift","Traktat","Trivialliteratur","Kolportageliteratur","Einblattdruck","Flugschrift","Streitschrift","Volksschrifttum","Volksbuch","Theaterzettel","Flugblatt","Tabelle","Zeitung","Zeitschrift")
```


# FBS genres by year (links of interest).
# The below plots depicts the genre frequency of FBS publications by year for links of interest.
```{r}
genres_fbs_1_1 <- fbs_links_of_interest_matches %>%
  inner_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  inner_join(vd17_genres_local%>%
              filter(genre %in% genre_list1_1), by = c("record_number"))%>%
  inner_join(vd17_titles_local %>% select(record_number,title)) %>%
  select(record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,genre)

phase_genres_fbs_1_1 <- genres_fbs_1_1%>%
  select(vd17_id,record_number,normalized_year,genre)%>%
  distinct(vd17_id,record_number,normalized_year,genre)%>%
  na.omit(genres_fbs_1_1)%>%
  group_by(normalized_year) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(phase = case_when(
    normalized_year < 1617 ~ "< 1617",
    normalized_year >= 1617 & normalized_year <= 1650 ~ "phase 1",
    normalized_year >= 1651 & normalized_year <= 1667 ~ "phase 2",
    normalized_year >= 1668 & normalized_year <= 1682 ~ "phase 3",
    normalized_year > 1682 ~ "> 1682"
  ))


phase_genres_fbs_1_1%>%
  ggplot(aes(x=normalized_year,y=n,fill=phase))+
  geom_col()+
  facet_wrap(~genre, scales="free_y")+
  xlab("Year") + ylab("All_FBS-Genre_category1")+
  scale_x_continuous(breaks = seq(1000, 2000, by = 10))+
  theme_hsci_discrete()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```
```{r}
genres_fbs_1_2 <- fbs_links_of_interest_matches %>%
  inner_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  inner_join(vd17_genres_local%>%
              filter(genre %in% genre_list1_2), by = c("record_number"))%>%
  inner_join(vd17_titles_local %>% select(record_number,title)) %>%
  select(record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,genre)

phase_genres_fbs_1_2 <- genres_fbs_1_2%>%
  select(vd17_id,record_number,normalized_year,genre)%>%
  distinct(vd17_id,record_number,normalized_year,genre)%>%
  na.omit(genres_fbs_1_2)%>%
  group_by(normalized_year) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(phase = case_when(
    normalized_year < 1617 ~ "< 1617",
    normalized_year >= 1617 & normalized_year <= 1650 ~ "phase 1",
    normalized_year >= 1651 & normalized_year <= 1667 ~ "phase 2",
    normalized_year >= 1668 & normalized_year <= 1682 ~ "phase 3",
    normalized_year > 1682 ~ "> 1682"
  ))


phase_genres_fbs_1_2%>%
  ggplot(aes(x=normalized_year,y=n,fill=phase))+
  geom_col()+
  facet_wrap(~genre, scales="free_y")+
  xlab("Year") + ylab("All_FBS-Genre_category1")+
  scale_x_continuous(breaks = seq(1000, 2000, by = 10))+
  theme_hsci_discrete()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```

```{r}
genres_fbs_cat1_1 <- gs4_create(
  "genres_all_fbs_cat1_1",
  sheets = genres_fbs_1_1%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://sru.k10plus.de/vd17?version=2.0&operation=searchRetrieve&maximumRecords=10&startRecord=1&recordSchema=picaxml&query=pica.vds=',vd17_id,'","',vd17_id,'")'))))
genres_fbs_cat1_1

phase_genres_fbs_plot1_1 <- gs4_create(
  "phase_genres_all_fbs_cat1_1",
  sheets = phase_genres_fbs_1_1)
phase_genres_fbs_plot1_1
```

```{r}
genres_fbs_cat1_2 <- gs4_create(
  "genres_all_fbs_cat1_2",
  sheets = genres_fbs_1_2%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://sru.k10plus.de/vd17?version=2.0&operation=searchRetrieve&maximumRecords=10&startRecord=1&recordSchema=picaxml&query=pica.vds=',vd17_id,'","',vd17_id,'")'))))
genres_fbs_cat1_2

phase_genres_fbs_plot1_2 <- gs4_create(
  "phase_genres_all_fbs_cat1_2",
  sheets = phase_genres_fbs_1_2)
phase_genres_fbs_plot1_2
```
```{r}
genres_fbs_3_1 <- fbs_links_of_interest_matches %>%
  inner_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  inner_join(vd17_genres_local%>%
              filter(genre %in% genre_list3_1), by = c("record_number"))%>%
  inner_join(vd17_titles_local %>% select(record_number,title)) %>%
  select(record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,genre)

phase_genres_fbs_3_1 <- genres_fbs_3_1%>%
  select(vd17_id,record_number,normalized_year,genre)%>%
  distinct(vd17_id,record_number,normalized_year,genre)%>%
  na.omit(genres_fbs_3_1)%>%
  group_by(normalized_year) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(phase = case_when(
    normalized_year < 1617 ~ "< 1617",
    normalized_year >= 1617 & normalized_year <= 1650 ~ "phase 1",
    normalized_year >= 1651 & normalized_year <= 1667 ~ "phase 2",
    normalized_year >= 1668 & normalized_year <= 1682 ~ "phase 3",
    normalized_year > 1682 ~ "> 1682"
  ))


phase_genres_fbs_3_1%>%
  ggplot(aes(x=normalized_year,y=n,fill=phase))+
  geom_col()+
  facet_wrap(~genre, scales="free_y")+
  xlab("Year") + ylab("All_FBS-Genre_category3")+
  scale_x_continuous(breaks = seq(1000, 2000, by = 10))+
  theme_hsci_discrete()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```

```{r}
genres_fbs_3_2 <- fbs_links_of_interest_matches %>%
  inner_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  inner_join(vd17_genres_local%>%
              filter(genre %in% genre_list3_2), by = c("record_number"))%>%
  inner_join(vd17_titles_local %>% select(record_number,title)) %>%
  select(record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,genre)

phase_genres_fbs_3_2 <- genres_fbs_3_2%>%
  select(vd17_id,record_number,normalized_year,genre)%>%
  distinct(vd17_id,record_number,normalized_year,genre)%>%
  na.omit(genres_fbs_3_2)%>%
  group_by(normalized_year) %>%
  count(genre)%>%
  arrange(desc(n))%>%
  mutate(phase = case_when(
    normalized_year < 1617 ~ "< 1617",
    normalized_year >= 1617 & normalized_year <= 1650 ~ "phase 1",
    normalized_year >= 1651 & normalized_year <= 1667 ~ "phase 2",
    normalized_year >= 1668 & normalized_year <= 1682 ~ "phase 3",
    normalized_year > 1682 ~ "> 1682"
  ))


phase_genres_fbs_3_2%>%
  ggplot(aes(x=normalized_year,y=n,fill=phase))+
  geom_col()+
  facet_wrap(~genre, scales="free_y")+
  xlab("Year") + ylab("All_FBS-Genre_category3")+
  scale_x_continuous(breaks = seq(1000, 2000, by = 10))+
  theme_hsci_discrete()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```
```{r}
genres_fbs_cat3_1 <- gs4_create(
  "genres_all_fbs_cat3_1",
  sheets = genres_fbs_3_1%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://sru.k10plus.de/vd17?version=2.0&operation=searchRetrieve&maximumRecords=10&startRecord=1&recordSchema=picaxml&query=pica.vds=',vd17_id,'","',vd17_id,'")'))))
genres_fbs_cat3_1

phase_genres_fbs_plot3_1 <- gs4_create(
  "phase_genres_all_fbs_cat3_1",
  sheets = phase_genres_fbs_3_1)
phase_genres_fbs_plot3_1
```

```{r}
genres_fbs_cat3_2 <- gs4_create(
  "genres_all_fbs_cat3_2",
  sheets = genres_fbs_3_2%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://sru.k10plus.de/vd17?version=2.0&operation=searchRetrieve&maximumRecords=10&startRecord=1&recordSchema=picaxml&query=pica.vds=',vd17_id,'","',vd17_id,'")'))))
genres_fbs_cat3_2

phase_genres_fbs_plot3_2 <- gs4_create(
  "phase_genres_all_fbs_cat3_2",
  sheets = phase_genres_fbs_3_2)
phase_genres_fbs_plot3_2
```

