---
title: "FBS analysis"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = here::here())
library(here)
source(here("code/common_basis.R"), local = knitr::knit_global())
library(tidyverse)
library(gghsci)
library(gt)
p <- function(number) {
  return(format(number, scientific = FALSE, big.mark = ","))
}
pp <- function(percentage, accuracy = 0.01) {
  return(scales::percent(percentage, accuracy = accuracy))
}
```

```{r}
#vd17_auth_a %>% filter(a_record_number==16594,field_code==410,subfield_code=="a")
```


```{r}
list_rescue <- c("Palmen Orden","Palmen-Orden","Palmenorden","Fruchtbringend","Frucht-bringend","Frucht Bringend","Die deutsche Akademie des 17. Jahrhunderts - Fruchtbringende Gesellschaft","Akademie des 17. Jahrhunderts","Akademie des Siebzehnten Jahrhunderts","Deutsche Akademie des Siebzehnten Jahrhunderts","Deutsche Akademie des 17. Jahrhunderts","Palmenorden","Akademie des Siebzehnten Jahrhunderts","Akademie des 17. Jahrhunderts","Societas Fructifera","Frugtbringende Selskab","Fruitbearing Society","Sociedad Fructífera","Société des Fructifiants","Ordre du Palmier","Società dei Carpofori","Towarzystwo Owocodajne","Komunitas Fruitbearing","Плодоносное общество","丰收学会")

vd17_a_rescue <- vd17_a %>%
  mutate(value = str_replace_all(value, sql("CHR(0)"), "_")) %>%
  collect()%>%
  filter(grepl(paste(list_rescue, collapse="|"), value))%>%
  mutate(rescue_value=value,rescue_field=field_code)%>%
  select(record_number,rescue_value,rescue_field)%>%
  distinct()
```

```{r}
all_match <- read.csv(here("all_match.csv"))
all_match <- select (all_match, -c('X','full_name_vd17','normalized_year','field_number'))
all_match_subset <-  all_match%>%
  filter(
    field_code %in% c("028A", "028B", "028C"), # FBS GND has to appear in one of these fields
    is.na(role) | !role %in% c("ctb", "dte"), # normed role has to be unknown or not one of these
    is.na(role) | !(role == "oth" & field_code == "028C" & !is.na(role2) & str_detect(role2, "^Beiträger|^Mitwirkender")), # in field 028C, if role is other, role2 should not be one of these
    is.na(role2) | !str_detect(role2, !!!str_flatten(c(
      "^AdressatIn",
      "ErwähnteR",
      "GefeierteR",
      "Mitglied eines Ausschusses, der akademische Grade vergibt",
      "Normerlassende Gebietskörperschaft",
      "Praeses",
      "RespondentIn",
      "Sonstige Person, Familie und Körperschaft",
      "VerfasserIn eines Vorworts",
      "VerfasserIn von ergänzendem Text",
      "VerfasserIn von Zusatztexten",
      "VertragspartnerIn",
      "WidmendeR",
      "WidmungsempfängerIn",
      "ZensorIn"
    ), collapse = "|^"))
  )
```

```{r}
all_match_subset <- select(all_match_subset,-c('role'))
```


# Joining vd17_id with fbs_links_of_interest 
```{r}
fbs_links_of_interest_local <- fbs_links_of_interest_a %>%
  inner_join(fbs_metadata_a %>% select(GND,Member_number_new,First_name_new,Last_name_new,Society_name,DOB,DOD) %>% mutate(GND = str_c("gnd/", GND))) %>%
  inner_join(vd17_id_a) %>%
  mutate(member_number=Member_number_new,first_name=First_name_new,last_name=Last_name_new)%>%
  collect() %>%
  select(where(~!all(is.na(.x))))

fbs_links_of_interest_local <- select (fbs_links_of_interest_local, c('record_number','vd17_id','member_number','first_name', 'last_name','role2','field_code'))

```

```{r}
fbs_links_of_interest_matches <- rbind(fbs_links_of_interest_local,all_match_subset)

fbs_links_of_interest_matches <- fbs_links_of_interest_matches %>%
  distinct()

fbs_rescue <- fbs_links_of_interest_matches %>%
  merge(vd17_a_rescue, by=c("record_number"),all=TRUE)%>%
  distinct()
```


# Creating local tables of vd17 normalized years, genres, languages, id and title.
```{r}
vd17_normalized_years_local <- vd17_normalized_years_a %>%
  collect()
genre_list2 <- c("Educational","Schul- und Hochschulschriften","Hochschulschrift","Dissertation","Dissertationensammlung","Matrikel","Universitätsprogramm","Vorlesung","Vorlesungsverzeichnis","Jugendsachbuch","Rechenbuch","Schulbuch","Fibel","Lesebuch","Schulprogramm","Governmental","Amtsdruckschrift","Edikt","Gesetz","Gesetzesammlung","Kapitulation","Mandat","Privileg","Richtlinie","Verordnung","Vertrag","Judicial","Legal","Entscheidungssammlung","Fallsammlung","Konsiliensammlung","Konsilium","Satzung","Religious","Theological","Agende","Beichtspiegel","Bibel","Brevier","Gebet","Katechismus","Missale","Psalter","Rituale","Other Governmental and Institutional","Formularsammlung","Schreibmeisterbuch","Regesten","Urkundenbuch","Business","Mercantile","Anzeige","Subskriptionsanzeige","Meßrelation","Subskribentenliste","Verkaufskatalog","Antiquariatskatalog","Auktionskatalog","Buchhandelskatalog","Meßkatalog","War Related","Festungsbau","Kriegskunde","General Works","Bericht","Brief","Briefsammlung","Regelsammlung","Statistik","Streitschrift")

vd17_parts_of_multipart_works <- vd17_parts_of_multipart_works_a%>%
  collect()%>%
  mutate(multipart="multipart")

vd17_genres_local <- vd17_genres_a %>%
  collect()%>%
  filter(!genre %in% c(genre_list2))%>%
  mutate(genre_full=a)%>%
  select(record_number,genre,genre_full)

vd17_normalized_langs_local <- vd17_normalized_langs_a %>%
  collect()

vd17_id_local <- vd17_id_a %>%
  collect()

vd17_titles_local <- vd17_titles_a %>%
  collect()

vd17_corporate_authors_name <- vd17_a %>%
  filter(field_code %in% c("029A","029F","029G"),subfield_code %in% c("a"))%>%
  mutate(corporate_subfield_code_a=field_code,name_corporate=value)%>%
  select(record_number,corporate_subfield_code_a,name_corporate)%>%
  collect()

vd17_corporate_authors_gnd <- vd17_a %>%
  filter(field_code %in% c("029A","029F","029G"),subfield_code %in% c("7"))%>%
  mutate(corporate_subfield_code_7=field_code,gnd_corporate=value)%>%
  select(record_number,corporate_subfield_code_7,gnd_corporate)%>%
  collect()

vd17_corporate_authors_ppn <- vd17_a %>%
  filter(field_code %in% c("029A","029F","029G"),subfield_code %in% c("9"))%>%
  mutate(corporate_subfield_code_9=field_code,ppn_corporate=value)%>%
  select(record_number,corporate_subfield_code_9,ppn_corporate)%>%
  collect()

vd17_corporate_name_gnd <- merge(vd17_corporate_authors_name,vd17_corporate_authors_gnd, by=c("record_number"),all=TRUE)%>%
  distinct()
vd17_corporate <- merge(vd17_corporate_name_gnd,vd17_corporate_authors_ppn, by=c("record_number"),all=TRUE)%>%
  distinct()

vd17_genres_combined <- vd17_genres_local %>%
  group_by(record_number) %>% 
  mutate(combined_all_genres = toString(unique(genre_full)))%>%
  distinct(record_number,combined_all_genres)
```


```{r}
library("writexl")
genre_fbs <- fbs_rescue %>%
  left_join(vd17_genres_local, by = c("record_number"))

fbs_with_no_genre <- genre_fbs%>%
  filter(is.na(genre))%>%
  left_join(vd17_corporate, by=c("record_number"))%>%
  distinct()

fbs_no_genre <- fbs_with_no_genre %>%
  inner_join(vd17_normalized_years_local, by = c("record_number")) %>%
  filter(normalized_year >= 1600, normalized_year <= 1700) %>%
  filter(nchar(normalized_year)==4)%>%
  left_join(vd17_titles_local %>% select(record_number,title),by = c("record_number")) %>%
  left_join(vd17_normalized_langs_local%>% select(record_number, publication_language, original_language), by = c("record_number"))%>%
  left_join(vd17_parts_of_multipart_works,by=c("record_number"))%>%
  select(record_number,normalized_year,vd17_id,title,member_number,first_name,last_name,role2,field_code,original_language,publication_language,genre,rescue_value,rescue_field,corporate_subfield_code_a,corporate_subfield_code_7,corporate_subfield_code_9,name_corporate,gnd_corporate,ppn_corporate,multipart)

write_xlsx(fbs_no_genre, "fbs_no_genre.xlsx")
```
```{r}
fbs_no_genres <- gs4_create(
  "fbs_no_genres",
  sheets = fbs_no_genre%>%
     mutate(vd17_id=gs4_formula(str_c('=HYPERLINK("https://kxp.k10plus.de/DB=1.28/CMD?ACT=SRCHA&IKT=8079&TRM=%27',vd17_id,'%27","',vd17_id,'")'))))
fbs_no_genres
```

