---
title: "FBS analysis"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = here::here())
library(here)
source(here("code/common_basis.R"), local = knitr::knit_global())
library(tidyverse)
library(gghsci)
library(gt)
p <- function(number) {
  return(format(number, scientific = FALSE, big.mark = ","))
}
pp <- function(percentage, accuracy = 0.01) {
  return(scales::percent(percentage, accuracy = accuracy))
}
```

```{r}
all_gnd_vd17 <- vd17_a %>%
  filter(subfield_code=="7")%>%
  select(record_number,field_code, value)%>%
  mutate(GND=value)%>%
  distinct(GND)%>%
  collect()

gnd_vd17 <- gs4_create(
  "sheets-gnd_vd17",
  sheets = all_gnd_vd17)

gnd_vd17

```


```{r install_python_packages}
#reticulate::py_install("pandas")
```

```{python}
#import urllib.request 

#ids=[]

#j=0
#for id in r.all_gnd_vd17['GND']:
  
    #if j%10000==0:
        #print(j)
    #try:
        #result=urllib.request.urlretrieve("http://d-nb.info/"+id+"/about/marcxml", "gnds/"+id+".xml")
        
    #except:
        #ids.append(id)
        #pass
    #j+=1

```

```{r}
#list <- list.files(path="code/narges/gnds/gnd")

#list_gnd=as.list(all_gnd_vd17$GND)
#for (i in list_gnd)
#{
  #j <- sub("gnd/","",i)
  #j <- paste(j,".xml",sep="")
  #result <- j %in% list
  #if (result==FALSE)
  #{print(j)}
#}

```

```{r}
all_gnd_vd17$GND<-gsub("gnd/","",as.character(all_gnd_vd17$GND))
gnd_authority <- read_tsv(here("code/narges/gnds/gnd/all_gnd.tsv"), lazy = TRUE)
authority_gnd_list <- gnd_authority[gnd_authority$value %in% all_gnd_vd17$GND, , drop = FALSE] %>%
  distinct(value)
gnd_authority_filter <- gnd_authority %>%
  filter(subfield_code=="a",field_code %in% c("024","375"))
```

```{r warning=FALSE}
#For some gnds, there is not field_code "375", so gender is not specified.
columns= c("GND","gender") 

genders = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  
colnames(genders) = columns
  

j <- 1
list_gnd_auth <- as.list(authority_gnd_list$value)
for (i in list_gnd_auth)
{
  gen=""
  record1 <- gnd_authority_filter[(gnd_authority_filter$value==i&gnd_authority_filter$field_code=="024"&gnd_authority_filter$subfield_code=="a"),]
  if (length(rownames(record1))>0)
  {rn <- record1$record_number
  record2 <- gnd_authority_filter[(gnd_authority_filter$record_number==rn&gnd_authority_filter$field_code=="375"&gnd_authority_filter$subfield_code=="a"),]
  if (length(rownames(record2))>0)
  {gen <- record2$value}
  }
  genders[j, ] <- c(i, gen)
  j <- j+1
}

```

```{r}
gnd_gender <- gs4_create(
  "sheets-gnd_gender",
  sheets = genders)

gnd_gender
```


