---
title: "FBS analysis"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = here::here())
library(here)
source(here("code/common_basis.R"), local = knitr::knit_global())
library(tidyverse)
library(gghsci)
library(gt)
p <- function(number) {
  return(format(number, scientific = FALSE, big.mark = ","))
}
pp <- function(percentage, accuracy = 0.01) {
  return(scales::percent(percentage, accuracy = accuracy))
}
```


```{r}
vd17_roles <- vd17_a %>%
  filter(field_code %in% c("028A", "028B", "028C", "028G"), subfield_code == "4") %>%
  mutate(role = value) %>%
  inner_join(vd17_id_a, by = c("record_number")) %>%
  left_join(vd17_normalized_years_a %>% select(record_number, normalized_year), by = c("record_number")) %>%
  filter(nchar(normalized_year) == 4) %>%
  select(normalized_year, vd17_id, record_number, field_number, field_code, subfield_code, role) %>%
  collect()

vd17_roles2 <- vd17_a %>%
  filter(field_code %in% c("028A", "028B", "028C", "028G"), subfield_code == "B") %>%
  mutate(role2 = value) %>%
  inner_join(vd17_id_a, by = c("record_number")) %>%
  left_join(vd17_normalized_years_a %>% select(record_number, normalized_year), by = c("record_number")) %>%
  filter(nchar(normalized_year) == 4) %>%
  select(normalized_year, vd17_id, record_number, field_number, field_code, subfield_code, role2) %>%
  collect()

write.csv(vd17_roles, "vd17_roles.csv")
write.csv(vd17_roles2, "vd17_roles2.csv")
```
