---
title: "VD17 master link data evaluation"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
source(here::here("code/common_basis.R"), local = knitr::knit_global())
```

```{r}
library(googlesheets4)
```

```{r}
add_metadata_fields <- function(df) {
  df %>%
    left_join(vd17_id_a) %>%
    left_join(vd17_titles_a %>% select(record_number, title)) %>%
    left_join(vd17_normalized_langs_a %>% distinct(record_number, publication_language) %>% group_by(record_number) %>% summarize(publication_language = str_flatten(publication_language, collapse = "|"))) %>%
    left_join(vd17_genres_a %>% distinct(record_number, genre) %>% group_by(record_number) %>% summarize(genre = str_flatten(genre, collapse = "|")))
}
```

```{r}
old_master_links <- read_sheet(ss = "1rXnOSB7P6vhJ5kTPu33upwZM__b0vx602vzBN63FaBw", sheet = "VD17 <-> FBS master link data")
```

```{r}
fbs_links_eval <- fbs_links_a %>%
  left_join(fbs_match_values_a %>% select(member_number, match_key)) %>%
  left_join(vd17_person_links_a %>% select(-GND)) %>%
  left_join(fbs_gnds_a) %>%
  left_join(fbs_metadata_a %>% select(member_number = Member_number_new, First_name_new, Last_name_new, Society_name)) %>%
  left_join(fbs_links_of_interest_a %>%
    select(record_number, field_number, field_code, member_number) %>%
    mutate(actor_relationship_relevant = TRUE)) %>%
  replace_na(list(actor_relationship_relevant = FALSE)) %>%
  compute_a(unique_indexes = list(c("record_number", "field_number", "field_code", "member_number")))
```


```{r}
fbs_links_eval %>%
  add_metadata_fields() %>%
  collect() %>%
  left_join(old_master_links %>% distinct(vd17_id, field_number, manual_override, notes)) %>%
  arrange(desc(actor_relationship_relevant), method, vd17_id, member_number) %>%
  relocate(actor_relationship_relevant, manual_override, notes, method, match_key, vd17_id, title, publication_language, genre, member_number, GND, First_name_new, Last_name_new, Society_name, role, role2, field_code) %>%
  hyperlink_vd17_id() %>%
  sheet_write(ss = "1rXnOSB7P6vhJ5kTPu33upwZM__b0vx602vzBN63FaBw", sheet = "VD17 <-> FBS master link data")
```

```{r}
old_master_records <- read_sheet(ss = "1rXnOSB7P6vhJ5kTPu33upwZM__b0vx602vzBN63FaBw", sheet = "VD17 <-> FBS master record data")
```

```{r}
fbs_records_eval <- fbs_links_eval %>%
  group_by(record_number) %>%
  summarise(is_core_society = any(actor_relationship_relevant), match_key = str_flatten(match_key, collapse = "&"), .groups = "drop") %>%
  mutate(method = "Society-associated actor") %>%
  union_all(
    fbs_rescue_records_a %>%
      transmute(record_number, method = "Rescue", match_key = value, is_core_society = TRUE)
  ) %>%
  group_by(record_number) %>%
  summarise(is_core_society = any(is_core_society), method = sql("GROUP_CONCAT(method ORDER BY method SEPARATOR '&')"), match_key = sql("GROUP_CONCAT(match_key ORDER BY match_key SEPARATOR '&')"), .groups = "drop") %>%
  compute_a(unique_indexes = list(c("record_number")))
```

```{r}
fbs_records_eval %>%
  add_metadata_fields() %>%
  collect() %>%
  left_join(old_master_records %>% distinct(vd17_id, manual_override, notes)) %>%
  arrange(desc(is_core_society), method, vd17_id) %>%
  relocate(is_core_society, manual_override, notes, method, match_key, vd17_id, title, publication_language, genre) %>%
  hyperlink_vd17_id() %>%
  sheet_write(ss = "1rXnOSB7P6vhJ5kTPu33upwZM__b0vx602vzBN63FaBw", sheet = "VD17 <-> FBS master record data")
```
