---
title: "Create tables in database"
output:
  html_notebook:
    code_folding: hide
    toc: yes
---

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = here::here())
library(keyring)
library(DBI)
library(RMariaDB)
library(assertthat)
rm(con)
while (!exists("con")) {
  tryCatch(con <- dbConnect(
    drv = MariaDB(),
    host = "vm2505.kaj.pouta.csc.fi",
    dbname = "vd17_analysis",
    user = "vd17-rw",
    password = key_get("vd17_analysis", "vd17-rw"),
    bigint = "integer",
    load_data_local_infile = TRUE,
    autocommit = TRUE,
    reconnect = TRUE
  ), error = function(e) {
    print(e)
    key_set("vd17_analysis", "vd17-rw")
  })
}
source(here::here("src/common_basis.R"), local = knitr::knit_global())

high_german_replacements_l <- c(
  "dzsch" = "sch",
  "dsch" = "z",
  "schm" = "sm",
  "aeu" = "eu",
  "ae" = "a",
  "au" = "eu",
  "ai" = "ei",
  "ay" = "ei",
  "bf" = "f",
  "chs" = "c",
  "ch" = "c",
  "ck" = "c",
  "cs" = "c",
  "cz" = "c",
  "ds" = "z",
  "dz" = "z",
  "gh" = "c",
  "gs" = "x",
  "g" = "c",
  "j" = "i",
  "ks" = "x",
  "k" = "c",
  "oe" = "u",
  "oi" = "eu",
  "pf" = "f",
  "ph" = "f",
  "scl" = "sl",
  "p" = "b",
  "ts" = "sch",
  "tz" = "z",
  "t" = "d",
  "ue" = "u",
  "v" = "f",
  "w" = "f",
  "ß" = "ss",
  "ff" = "f",
  "y" = "i"
)
```


# Create core downstream tables from vd17_a/c

```{r create_core_downstream_tables}
vd17_normalized_years_a <- vd17_a %>%
  filter(field_code == "011@") %>%
  pivot_wider(id_cols = record_number:field_number, values_from = value, names_from = subfield_code) %>%
  collect() %>%
  mutate(normalized_year = as.integer(a)) %>%
  copy_to_a(con, name = dbplyr::in_schema("vd17", "vd17_normalized_years_a"), temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number", "field_number")))

vd17_normalized_years_c <- vd17_normalized_years_a %>%
  compute_c(name = dbplyr::in_schema("vd17", "vd17_normalized_years_c"), temporary = FALSE, overwrite = TRUE)

vd17_genres_a <- vd17_a %>%
  filter(field_code %in% c("044S", "013D"), value != " ") %>%
  pivot_wider(
    id_cols = record_number:field_number,
    values_from = value, names_from = subfield_code
  ) %>%
  mutate(a = a[!is.na(a)] %>% str_replace_all("^![^!]*!", "")) %>%
  mutate(genre = a[!is.na(a)] %>% str_replace_all(":.*", "")) %>%
  rename(full_genre = a) %>%
  compute_a(name = dbplyr::in_schema("vd17", "vd17_genres_a"), temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number", "field_number")))

vd17_genres_c <- vd17_genres_a %>%
  compute_c(name = dbplyr::in_schema("vd17", "vd17_genres_c"), temporary = FALSE, overwrite = TRUE)

vd17_normalized_locations_a <- vd17_a %>%
  filter(field_code == "033D") %>%
  collect() %>%
  pivot_wider(id_cols = record_number:field_number, values_from = value, names_from = subfield_code, values_fn = list) %>%
  rename(location = p, location_type = `4`) %>%
  unnest_cross(c(-record_number, -field_number), keep_empty = TRUE) %>%
  copy_to_a(con, name = dbplyr::in_schema("vd17", "vd17_normalized_locations_a"), temporary = FALSE, overwrite = TRUE, indexes = list(c("record_number", "field_number")))

vd17_normalized_locations_c <- vd17_normalized_locations_a %>%
  compute_c(name = dbplyr::in_schema("vd17", "vd17_normalized_locations_c"), temporary = FALSE, overwrite = TRUE)

vd17_normalized_langs_a <- vd17_a %>%
  filter(field_code == "010@") %>%
  collect() %>%
  pivot_wider(id_cols = record_number:field_number, values_from = value, names_from = subfield_code, values_fn = list) %>%
  rename(publication_language = a, original_language = c, intermediary_language = b) %>%
  unnest_cross(c(publication_language, original_language, intermediary_language), keep_empty = TRUE) %>%
  copy_to_a(con, name = dbplyr::in_schema("vd17", "vd17_normalized_langs_a"), temporary = FALSE, overwrite = TRUE, indexes = list(c("record_number", "field_number")))

vd17_normalized_langs_c <- vd17_normalized_langs_a %>%
  compute_c(name = dbplyr::in_schema("vd17", "vd17_normalized_langs_c"), temporary = FALSE, overwrite = TRUE)

vd17_titles_a <- vd17_a %>%
  filter(field_code == "021A") %>%
  pivot_wider(id_cols = record_number:field_number, values_from = value, names_from = subfield_code) %>%
  rename(title = a, additional_title = d, statement_of_responsibility = h) %>%
  mutate(combined_title = str_c(title, additional_title, statement_of_responsibility, sep = "/")) %>%
  compute_a(name = dbplyr::in_schema("vd17", "vd17_titles_a"), temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number", "field_number")))

vd17_titles_c <- vd17_titles_a %>%
  compute_c(name = dbplyr::in_schema("vd17", "vd17_titles_c"), temporary = FALSE, overwrite = TRUE)

vd17_record_types_a <- vd17_a %>%
  filter(field_code == "002@") %>%
  mutate(record_type = case_match(
    value,
    "Aau" ~ "Single-part publication",
    "Afu" ~ "Part of multi-part publication",
    "Acu" ~ "Unified multi-part publication"
  )) %>%
  compute_a(name = "vd17_record_types_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number")))

vd17_record_types_c <- vd17_record_types_a %>%
  compute_a(name = "vd17_record_types_c", temporary = FALSE, overwrite = TRUE)

vd17_person_links_a <- vd17_a %>%
  filter(
    field_code %in% c("028A", "028B", "028C", "028G")
  ) %>%
  pivot_wider(
    id_cols = c(record_number, field_number, field_code),
    values_from = value, names_from = subfield_code
  ) %>%
  rename(GND = `7`, role = `4`, role2 = B, ppn = `9`, personal_name = `P`, family_name = `A`, first_names = `D`, count = `N`, prefix = `C`, epithet = `L`, date_of_birth = `E`, date_of_death = `M`) %>%
  mutate(
    combined_name =
      if_else(is.na(prefix), "", str_c(prefix, " ")) %>%
        str_c(str_c(family_name, first_names, if_else(is.na(personal_name) & is.na(count), NA_character_, str_c(personal_name, count, sep = " ")), epithet, sep = ", ")) %>%
        str_c(if_else(!is.na(date_of_birth) | !is.na(date_of_death), str_c(" (", date_of_birth, "-", date_of_death, ")"), ""))
  ) %>%
  compute_a(name = "vd17_person_links_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number", "field_number", "field_code")))

vd17_person_links_c <- vd17_person_links_a %>%
  compute_c(name = "vd17_person_links_c", temporary = FALSE, overwrite = TRUE)

vd17_corporate_links_a <- vd17_a %>%
  filter(
    field_code %in% c("029A", "029F", "029G")
  ) %>%
  pivot_wider(
    id_cols = c(record_number, field_number, field_code),
    values_from = value, names_from = subfield_code
  ) %>%
  rename(GND = `7`, role = `4`, role2 = B, ppn = `9`, preferred_name = A, location = C, date = D, child_entity = F, addition = G) %>%
  mutate(combined_name = str_c(preferred_name, child_entity, addition, location, date, sep = ", ")) %>%
  compute_a(name = "vd17_corporate_links_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number", "field_number", "field_code")))

vd17_corporate_links_c <- vd17_corporate_links_a %>%
  compute_c(name = "vd17_corporate_links_c", temporary = FALSE, overwrite = TRUE)

vd17_fingerprints_a <- vd17_a %>%
  filter(field_code == "007P", subfield_code == "0") %>%
  mutate(value = str_replace_all(value, " +", " ")) %>%
  collect() %>%
  separate_wider_position(value, c(f1_1 = 2, f1_2 = 2, 1, f2_1 = 2, f2_2 = 2, 1, f3_1 = 2, f3_2 = 2, 1, f4_1 = 2, f4_2 = 2, 1, f34_source = 1, 1, year = 4, year_source = 1), too_few = "align_start", too_many = "drop") %>%
  select(record_number, f1_1:year_source) %>%
  copy_to_a(con, name = "vd17_fingerprints_a", temporary = FALSE, overwrite = TRUE, indexes = list(c("record_number")))

vd17_fingerprints_c <- vd17_fingerprints_a %>%
  compute_c(name = "vd17_fingerprints_c", temporary = FALSE, overwrite = TRUE)

vd17_wide_a <- vd17_a %>%
  select(record_number, field_code:value) %>%
  mutate(value = str_replace_all(value, sql("CHR(0)"), "_")) %>%
  pivot_wider(id_cols = record_number, names_from = field_code:subfield_code, values_from = value, values_fn = ~ str_flatten(., collapse = "|")) %>%
  compute_a(name = dbplyr::in_schema("vd17", "vd17_wide_a"), temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number")))

vd17_wide_c <- vd17_wide_a %>%
  compute_c(name = dbplyr::in_schema("vd17", "vd17_wide_c"), temporary = FALSE, overwrite = TRUE)
```

# Variant mapping

## Key generation

```{r}
form_factors <- vd17_a %>%
  filter(field_code == "034I") %>%
  distinct(record_number, form_factor = value) %>%
  group_by(record_number) %>%
  dbplyr::window_order(form_factor) %>%
  summarize(form_factors = str_flatten(form_factor, collapse = "|"), .groups = "drop") %>%
  #  compute_c()
  collect() %>%
  copy_to_c(con)

places_of_publication <- vd17_normalized_locations_a %>%
  filter(location_type == "pup") %>%
  select(record_number, place_of_publication = location)
places_of_production <- vd17_normalized_locations_a %>%
  filter(location_type == "mfp") %>%
  select(record_number, place_of_production = location)
places_of_distribution <- vd17_normalized_locations_a %>%
  filter(location_type == "dbp") %>%
  select(record_number, place_of_distribution = location)

unified_places_of_publication <- vd17_a %>%
  distinct(record_number) %>%
  left_join(places_of_publication, join_by(record_number)) %>%
  left_join(places_of_production, join_by(record_number)) %>%
  left_join(places_of_distribution, join_by(record_number)) %>%
  mutate(place_of_publication = coalesce(place_of_publication, place_of_production, place_of_distribution)) %>%
  filter(!is.na(place_of_publication)) %>%
  mutate(place_of_publication = str_replace_all(str_to_lower(place_of_publication), "[^a-zß]", "")) %>%
  distinct(record_number, place_of_publication) %>%
  group_by(record_number) %>%
  dbplyr::window_order(place_of_publication) %>%
  summarize(places_of_publication = str_flatten(place_of_publication, collapse = "|"), .groups = "drop") %>%
  #  compute_c()
  collect() %>%
  copy_to_c(con)

rda_printers <- vd17_a %>%
  filter(field_code == "029F", subfield_code == "4", value == "prt") %>%
  select(record_number, field_number) %>%
  inner_join(vd17_a %>% filter(subfield_code == "7"), join_by(record_number, field_number)) %>%
  select(record_number, printer_gnd = value)

printers <- vd17_a %>%
  filter(field_code == "033J", subfield_code == "7") %>%
  select(record_number, printer_gnd = value)

additional_printers <- vd17_a %>%
  filter(field_code == "028C", (subfield_code == "4" & value == "prt") | (subfield_code == "B" & str_detect(value, "^Drucker|^Verleger"))) %>%
  distinct(record_number, field_number) %>%
  inner_join(vd17_a %>% filter(subfield_code == "7"), join_by(record_number, field_number)) %>%
  select(record_number, printer_gnd = value)

all_printers <- rda_printers %>%
  union_all(printers) %>%
  union_all(additional_printers) %>%
  distinct(record_number, printer_gnd) %>%
  group_by(record_number) %>%
  dbplyr::window_order(printer_gnd) %>%
  summarize(printer_gnds = str_flatten(printer_gnd, collapse = "|"), .groups = "drop") %>%
  #  compute_c()
  collect() %>%
  copy_to_c(con)

vd17_titlekeys_c <- vd17_titles_a %>%
  mutate(title = str_replace_all(str_to_lower(title), "[^a-zß]", "")) %>%
  select(record_number, title) %>%
  collect() %>%
  mutate(title = str_replace_all(title, high_german_replacements_l)) %>%
  copy_to_c(con)
```

## Variant table calculation

```{r variants}
vd17_explicitly_mapped_variants <- vd17_a %>%
  filter(field_code == "037A", str_detect(value, "nicht ident|identisch|variant")) %>%
  collect() %>%
  mutate(vd17_id = str_extract_all(value, "\\b[0-9]+:[0-9]+.\\b")) %>%
  unnest(vd17_id) %>%
  distinct(record_number, vd17_id) %>%
  copy_to_a(con) %>%
  inner_join(vd17_id_a, join_by(vd17_id)) %>%
  select(record_number.x, record_number.y) %>%
  compute_a()

vd17_explicitly_mapped_variants <- vd17_explicitly_mapped_variants %>%
  union_all(vd17_explicitly_mapped_variants %>% rename(record_number.x = record_number.y, record_number.y = record_number.x)) %>%
  filter(record_number.x < record_number.y) %>%
  distinct(record_number.x, record_number.y) %>%
  compute_a()

t <- vd17_titlekeys_c %>%
  select(record_number, title) %>%
  #  inner_join(vd17_normalized_years_c %>% select(record_number, normalized_year)) %>%
  left_join(unified_places_of_publication) %>%
  left_join(all_printers) %>%
  inner_join(vd17_page_counts_c %>% mutate(page_count_low = page_count - pmin(floor(page_count / 3), 3), page_count_high = page_count + pmin(floor(page_count / 3), 3))) %>%
  #  inner_join(extents) %>%
  left_join(form_factors) %>%
  replace_na(list(form_factors = "[UNKNOWN]", printer_gnds = "[UNKNOWN]", places_of_publication = "[UNKNOWN]")) %>%
  compute_c()

vd17_identical_metadata <- t %>%
  inner_join(t, join_by(title, places_of_publication, printer_gnds, page_count >= page_count_low, page_count <= page_count_high, form_factors, record_number < record_number)) %>%
  select(record_number.x, record_number.y, title, places_of_publication, printer_gnds, page_count.x, page_count.y, form_factors) %>%
  left_join(vd17_fingerprints_c, join_by(record_number.x == record_number)) %>%
  left_join(vd17_fingerprints_c, join_by(record_number.y == record_number)) %>%
  collect() %>%
  mutate(fpsame = (f1_1.x == f1_1.y & f1_2.x == f1_2.y) + (f2_1.x == f2_1.y & f2_2.x == f2_2.y) + (f3_1.x == f3_1.y & f3_2.x == f3_2.y) + (f4_1.x == f4_1.y & f4_2.x == f4_2.y)) %>%
  filter(fpsame >= 2, year.x == year.y) %>%
  copy_to_a(con)

vd17_identical_fingerprints <- vd17_fingerprints_c %>%
  inner_join(vd17_page_counts_c) %>%
  inner_join(vd17_fingerprints_c %>% inner_join(vd17_page_counts_c %>% mutate(page_count_low = page_count - pmin(floor(page_count / 3), 3), page_count_high = page_count + pmin(floor(page_count / 3), 3))), join_by(f1_1, f1_2, f2_1, f2_2, f3_1, f3_2, f4_1, f4_2, f34_source, year, record_number < record_number, page_count >= page_count_low, page_count <= page_count_high)) %>%
  select(record_number.x, record_number.y) %>%
  compute_a()

vd17_variants <- vd17_explicitly_mapped_variants %>%
  union(vd17_identical_metadata %>% select(record_number.x, record_number.y)) %>%
  union(vd17_identical_fingerprints) %>%
  inner_join(
    vd17_record_types_a %>% select(record_number.x = record_number, record_type.x = record_type)
  ) %>%
  inner_join(
    vd17_record_types_a %>% select(record_number.y = record_number, record_type.y = record_type)
  ) %>%
  filter(record_type.x == record_type.y) %>%
  select(record_number.x, record_number.y) %>%
  compute_a(name = "vd17_variants", unique_indexes = list(c("record_number.x", "record_number.y"), c("record_number.y", "record_number.x")), temporary = TRUE, overwrite = TRUE)

vd17_variant_mapping_a <- tbl(con, sql("
WITH RECURSIVE final_record_number AS (
  SELECT `record_number.x`, `record_number.y`
  FROM vd17_variants
  UNION
  SELECT t.`record_number.x`, o.`record_number.y`
  FROM final_record_number t, vd17_variants o
  WHERE t.`record_number.y`=o.`record_number.x`
)
SELECT `record_number.x` AS record_number, `record_number.y` AS source_record_number FROM final_record_number")) %>%
  group_by(source_record_number) %>%
  filter(record_number == min(record_number)) %>%
  ungroup() %>%
  compute_a(name = "vd17_variant_mapping_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("source_record_number", "record_number")))

vd17_variant_mapping_c <- vd17_variant_mapping_a %>%
  compute_c(name = "vd17_variant_mapping_c", temporary = FALSE, overwrite = TRUE)
```

# Authority data table creation

```{r create_auth_tables}
vd17_auth_id_a <- vd17_auth_a %>%
  filter(field_code == "024", subfield_code == "2", value == "gnd") %>%
  select(a_record_number, field_number) %>%
  inner_join(vd17_auth_a %>% filter(subfield_code == "a")) %>%
  mutate(GND = str_c("gnd/", value)) %>%
  select(a_record_number, GND) %>%
  collect() %>%
  copy_to_a(con, name = "vd17_auth_id_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("a_record_number", "GND"), c("GND", "a_record_number")))

vd17_auth_id_c <- vd17_auth_id_a %>%
  compute_c(name = "vd17_auth_id_c", temporary = FALSE, overwrite = TRUE)

vd17_auth_gender_a <- vd17_auth_a %>%
  filter(field_code == "375", subfield_code == "a") %>%
  mutate(gender = case_when(
    value == 1 ~ "male",
    value == 2 ~ "female",
    value == 9 ~ "not applicable",
    value == 0 ~ NA_character_
  )) %>%
  select(a_record_number, gender) %>%
  filter(!is.na(gender)) %>%
  compute_a(name = "vd17_auth_gender_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("a_record_number", "gender")))

vd17_auth_gender_c <- vd17_auth_gender_a %>%
  compute_c(name = "vd17_auth_gender_c", temporary = FALSE, overwrite = TRUE)

vd17_auth_name_a <- vd17_auth_a %>%
  filter(field_code == "100", subfield_code != "i") %>%
  mutate(value = case_when(
    subfield_code %in% c("b", "c", "d") ~ str_c(", ", value),
    subfield_code == "9" ~ str_c(" (", str_replace_all(value, "^v:", ""), ")"),
    T ~ value
  )) %>%
  pivot_wider(id_cols = a_record_number, names_from = subfield_code, values_from = value) %>%
  mutate(unified_name = str_c(a, b, c, d, t, `9`)) %>%
  select(a_record_number, unified_name) %>%
  collect() %>%
  copy_to_a(con, name = "vd17_auth_name_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("a_record_number", "unified_name")))

vd17_auth_name_c <- vd17_auth_name_a %>%
  compute_c(name = "vd17_auth_name_c", temporary = FALSE, overwrite = TRUE)
```

# Misc

```{r create_db_versions_of_genre_categorisations}
vd17_genre_categorisation_a <- read_sheet(ss = "1rXnOSB7P6vhJ5kTPu33upwZM__b0vx602vzBN63FaBw", sheet = "Genre categorisations") %>%
  select(-c(VD17:`Society-related`)) %>%
  copy_to_a(con, name = "vd17_genre_categorisation_a", unique_indexes = list(c("genre")), temporary = FALSE, overwrite = TRUE)

vd17_genre_categorisation_c <- vd17_genre_categorisation_a %>%
  compute_c(con, name = "vd17_genre_categorisation_c", temporary = FALSE, overwrite = TRUE)
```


# Create Fruit-Bearing Society tables

```{r create_fbs_tables}
fbs_metadata_gs <- read_sheet(ss = "1tYSIXhoeeHk92HsP93Wul4b1mDjlsKcavc9LOi4K6RU", sheet = "FBS_master_metadata", col_types = "c") %>%
  mutate(GND = str_c("gnd/", GND), alternate_GND = str_c("gnd/", alternate_GND), `Old GND` = str_c("gnd/", `Old GND`)) %>%
  relocate(Name)

fbs_metadata_a <- fbs_metadata_gs %>%
  copy_to_a(con, name = "fbs_metadata_a", temporary = FALSE, overwrite = TRUE, unique_indexes = c("GND"))

fbs_metadata_c <- fbs_metadata_a %>%
  compute_c(name = "fbs_metadata_c", temporary = FALSE, overwrite = TRUE)
```

```{r}
# FBS links

## Through GNDs

fbs_gnds_a <- fbs_metadata_a %>%
  select(member_number, GND) %>%
  union(
    fbs_metadata_a %>%
      select(member_number, GND = alternate_GND)
  ) %>%
  union(
    fbs_metadata_a %>%
      select(member_number, GND = `Old GND`)
  ) %>%
  filter(!is.na(GND)) %>%
  compute_a(name = "fbs_gnds_a", temporary = TRUE, overwrite = TRUE, unique_indexes = list(c("GND", "member_number")))

fbs_gnd_links_a <- vd17_a %>%
  inner_join(fbs_gnds_a, join_by(value == GND)) %>%
  select(record_number, field_number, field_code, member_number)

## Through name matching

prefixes_l <- vd17_person_links_a %>%
  filter(!is.na(prefix)) %>%
  count(prefix = str_to_lower(prefix)) %>%
  filter(n > 1) %>%
  collect() %>%
  mutate(prefix = str_c("\\b", str_escape(prefix), "\\b")) %>%
  arrange(desc(str_length(prefix))) %>%
  pull(prefix)

vd17_match_values_a <- vd17_person_links_a %>%
  mutate(personal_name = if_else(!is.na(count), str_c(personal_name, ", ", count), personal_name)) %>%
  select(record_number, field_number, field_code, GND, family_name, first_names, personal_name, epithet) %>%
  pivot_longer(family_name:epithet) %>%
  mutate(value = str_to_lower(value)) %>%
  filter(!is.na(value)) %>%
  collect() %>%
  pivot_wider() %>%
  mutate(match_key = case_when(
    !is.na(epithet) & !is.na(personal_name) ~ str_c(personal_name, epithet),
    !is.na(first_names) & !is.na(family_name) ~ str_c(family_name, first_names),
    T ~ NA_character_
  )) %>%
  mutate(match_key = str_replace_all(match_key, str_flatten(prefixes_l, collapse = "|"), "")) %>%
  mutate(match_key = str_replace_all(match_key, high_german_replacements_l)) %>%
  mutate(match_key = str_replace_all(match_key, "[^a-zß]", "")) %>%
  filter(!is.na(match_key), match_key != "") %>%
  copy_to_a(con, name = "vd17_match_values_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("record_number", "field_number", "field_code")), indexes = list(c("match_key")))

vd17_auth_match_values_a <- vd17_auth_a %>%
  filter(field_code %in% c("100", "400")) %>%
  pivot_wider(id_cols = a_record_number:field_number, values_from = value, names_from = subfield_code) %>%
  filter(str_length(str_replace_all(str_to_lower(a), "[^a-zß]", "")) >= 3) %>%
  mutate(match_key = str_to_lower(str_c(a, b, c))) %>%
  select(a_record_number, match_key) %>%
  collect() %>%
  mutate(match_key = str_replace_all(match_key, str_flatten(prefixes_l, collapse = "|"), "")) %>%
  mutate(match_key = str_replace_all(match_key, high_german_replacements_l)) %>%
  mutate(match_key = str_replace_all(match_key, "[^a-zß]", "")) %>%
  filter(!is.na(match_key), match_key != "") %>%
  distinct() %>%
  copy_to_a(con, name = "vd17_auth_match_values_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("a_record_number", "match_key")), indexes = list(c("match_key")))

fbs_match_values_a <- fbs_metadata_a %>%
  mutate(epithet = if_else(!is.na(Title_new), str_c(Last_name_new, ", ", Title_new), NA_character_), Last_name_new = if_else(!is.na(Title_new), NA_character_, Last_name_new)) %>%
  select(member_number, GND, First_name_new, Last_name_new, epithet) %>%
  pivot_longer(First_name_new:epithet) %>%
  mutate(value = str_to_lower(value)) %>%
  filter(!is.na(value)) %>%
  collect() %>%
  pivot_wider() %>%
  mutate(match_key = case_when(
    !is.na(epithet) & !is.na(First_name_new) ~ str_c(First_name_new, epithet),
    !is.na(First_name_new) & !is.na(Last_name_new) ~ str_c(Last_name_new, First_name_new),
    T ~ NA_character_
  )) %>%
  mutate(match_key = str_replace_all(match_key, str_flatten(prefixes_l, collapse = "|"), "")) %>%
  mutate(match_key = str_replace_all(match_key, high_german_replacements_l)) %>%
  mutate(match_key = str_replace_all(match_key, "[^a-zß]", "")) %>%
  filter(!is.na(match_key), match_key != "") %>%
  copy_to_a(con, name = "fbs_match_values_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("member_number")), indexes = list(c("match_key")))

fbs_match_links_a <- fbs_match_values_a %>%
  inner_join(vd17_match_values_a, join_by(match_key)) %>%
  mutate(method = "FBS match key") %>%
  union_all( # actual forms associated with GND links
    fbs_gnd_links_a %>%
      inner_join(vd17_match_values_a) %>%
      distinct(member_number, match_key) %>%
      inner_join(vd17_match_values_a) %>%
      mutate(method = "GND link match key")
  ) %>%
  union_all( # forms mined from authority data
    fbs_gnds_a %>%
      inner_join(vd17_auth_id_a) %>%
      inner_join(vd17_auth_match_values_a) %>%
      distinct(member_number, match_key) %>%
      inner_join(vd17_match_values_a) %>%
      mutate(method = "GND authority match key")
  ) %>%
  distinct(record_number, field_number, field_code, member_number, match_key, method) %>%
  left_join(vd17_person_links_a) %>%
  left_join(fbs_gnds_a, join_by(member_number)) %>%
  filter(is.na(GND.y) | is.na(GND.x) | GND.x == GND.y) %>%
  distinct(record_number, field_number, field_code, member_number, match_key, method) %>%
  compute_a(name = "fbs_match_links_a", temporary = FALSE, overwrite = TRUE)

fbs_links_a <- fbs_gnd_links_a %>%
  mutate(method = "GND") %>%
  union_all(
    fbs_match_links_a %>%
      select(-match_key)
  ) %>%
  group_by(record_number, field_number, field_code, member_number) %>%
  summarise(method = sql("GROUP_CONCAT(method ORDER BY method SEPARATOR '&')"), .groups = "drop") %>%
  compute_a(name = "fbs_links_a", unique_indexes = list(c("record_number", "field_number", "member_number")), temporary = FALSE, overwrite = TRUE)

fbs_links_c <- fbs_links_a %>%
  compute_c(name = "fbs_links_c", temporary = FALSE, overwrite = TRUE)
```

```{r}
fbs_manual_status_overrides_a <- read_sheet(ss = "1rXnOSB7P6vhJ5kTPu33upwZM__b0vx602vzBN63FaBw", sheet = "VD17 <-> FBS master record data") %>%
  filter(!is.na(manual_status_override)) %>%
  select(vd17_id, manual_status_override) %>%
  copy_to_a(con, name = "fbs_manual_status_overrides_a", unique_indexes = list(c("vd17_id")), temporary = FALSE, overwrite = TRUE)

fbs_manual_status_overrides_c <- fbs_manual_status_overrides_a %>%
  compute_c(name = "fbs_manual_status_overrides_c", temporary = FALSE, overwrite = TRUE)
```

```{r rescue_recors}
fbs_rescue_records_a <- vd17_a %>%
  filter(str_detect(value, !!!str_flatten(c(
    "Palmen Orden",
    "Palmen-Orden",
    "Palmenorden",
    "Fruchtbringend",
    "Frucht-bringend",
    "Frucht Bringend",
    "Die deutsche Akademie des 17. Jahrhunderts - Fruchtbringende Gesellschaft",
    "Akademie des 17. Jahrhunderts",
    "Akademie des Siebzehnten Jahrhunderts",
    "Deutsche Akademie des Siebzehnten Jahrhunderts",
    "Deutsche Akademie des 17. Jahrhunderts",
    "Akademie des Siebzehnten Jahrhunderts",
    "Akademie des 17. Jahrhunderts",
    "Societas Fructifera",
    "Frugtbringende Selskab",
    "Fruitbearing Society",
    "Sociedad Fructífera",
    "Société des Fructifiants",
    "Ordre du Palmier",
    "Società dei Carpofori",
    "Towarzystwo Owocodajne",
    "Komunitas Fruitbearing",
    "Плодоносное общество",
    "丰收学会",
    "palmen orden",
    "palmen-orden",
    "palmenorden",
    "fruchtbringend",
    "frucht-bringend",
    "frucht bringend",
    "die deutsche akademie des 17. jahrhunderts - fruchtbringende gesellschaft",
    "akademie des 17. jahrhunderts",
    "akademie des siebzehnten jahrhunderts",
    "deutsche akademie des siebzehnten jahrhunderts",
    "deutsche akademie des 17. jahrhunderts",
    "akademie des siebzehnten jahrhunderts",
    "akademie des 17. jahrhunderts",
    "societas fructifera",
    "frugtbringende selskab",
    "fruitbearing society",
    "sociedad fructífera",
    "société des fructifiants",
    "ordre du palmier",
    "società dei carpofori",
    "towarzystwo owocodajne",
    "komunitas fruitbearing"
  ), collapse = "|"))) %>%
  compute_a(name = "fbs_rescue_records_a", indexes = list(c("record_number")), temporary = FALSE, overwrite = TRUE)

fbs_rescue_records_c <- fbs_rescue_records_a %>%
  compute_c(name = "fbs_rescue_records_c", temporary = FALSE, overwrite = TRUE)
```

```{r}
# Filtering down society subset

fbs_links_of_interest_a <- fbs_links_a %>%
  inner_join(vd17_person_links_a, join_by(record_number, field_number, field_code)) %>%
  filter(
    field_code %in% c("028A", "028B", "028C"), # FBS GND has to appear in one of these fields
    is.na(role) | !role %in% c("ctb", "dte"), # normed role has to be unknown or not one of these
    is.na(role2) | !str_detect(role2, !!!str_flatten(c( # role2 should not be one of these
      "^Adressat",
      "Erwähnte",
      "Gefeierte",
      "Mitglied eines Ausschusses, der akademische Grade vergibt",
      "Normerlassende Gebietskörperschaft",
      "Praeses",
      "Respondent",
      "Sonstige Person, Familie und Körperschaft",
      "Verfasser",
      "Vertragspartner",
      "Widmende",
      "Widmungsempfänger",
      "Drucker",
      "Zensor",
      "Beiträger",
      "GeistigeR Schöpfer",
      "Mitwirkender",
      "Herausgeber",
      "Angeklagte",
      "Auftraggeber"
    ), collapse = "|^"))
  ) %>%
  select(record_number, field_number, field_code, member_number, method) %>%
  compute_a(name = "fbs_links_of_interest_a", indexes = list(c("record_number")), temporary = FALSE, overwrite = TRUE)

fbs_links_of_interest_c <- fbs_links_of_interest_a %>%
  compute_c(name = "fbs_links_of_interest_c", temporary = FALSE, overwrite = TRUE)
```

## FBS record set generation

```{r}
fbs_auto_records_a <- fbs_links_a %>%
  select(record_number) %>%
  left_join(fbs_links_of_interest_a %>% select(record_number) %>% mutate(method = "Society-associated contributor")) %>%
  replace_na(list(method = "Society-associated other actor")) %>%
  union_all(fbs_rescue_records_a %>%
    select(record_number) %>%
    mutate(method = "Rescue")) %>%
  inner_join(vd17_id_a) %>%
  left_join(vd17_genres_a) %>%
  left_join(vd17_genre_categorisation_a) %>%
  group_by(vd17_id) %>%
  summarise(
    auto_status = case_when(
      any(method != "Society-associated other actor") & any(group_1 == "Society-unrelated") ~ "Member substantive role",
      any(method != "Society-associated other actor") & any(group_1 == "Society-related") ~ "Member substantive role and society purpose related",
      any(method != "Society-associated other actor") ~ "Member substantive role",
      T ~ "Member linked"
    ),
    method = sql("GROUP_CONCAT(method ORDER BY method SEPARATOR '&')"),
    .groups = "drop"
  ) %>%
  compute_a(name = "fbs_auto_records_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("vd17_id")))

fbs_auto_records_c <- fbs_auto_records_a %>%
  compute_c(name = "fbs_auto_records_c", temporary = FALSE, overwrite = TRUE)

fbs_raw_records_a <- fbs_auto_records_a %>%
  anti_join(vd17_record_types_a %>%
    filter(record_type == "Unified multi-part publication") %>%
    inner_join(vd17_id_a)) %>%
  rename(status = auto_status) %>%
  anti_join(fbs_manual_status_overrides_a) %>%
  union_all(fbs_manual_status_overrides_a %>% filter(manual_status_override != "Not member linked") %>% rename(status = manual_status_override) %>% mutate(method = "Manual")) %>%
  left_join(
    vd17_variant_mapping_a %>%
      inner_join(vd17_id_a, join_by(record_number)) %>%
      inner_join(vd17_id_a %>%
        rename(source_record_number = record_number, source_vd17_id = vd17_id), join_by(source_record_number)) %>%
      select(unified_vd17_id = vd17_id, vd17_id = source_vd17_id)
  ) %>%
  mutate(unified_vd17_id = coalesce(unified_vd17_id, vd17_id)) %>%
  compute_a(name = "fbs_raw_records_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("vd17_id")))

fbs_raw_records_c <- fbs_raw_records_a %>%
  compute_c(name = "fbs_raw_records_c", temporary = FALSE, overwrite = TRUE)

fbs_records_a <- fbs_raw_records_a %>%
  distinct(vd17_id = unified_vd17_id, set = status, method) %>%
  group_by(vd17_id) %>%
  summarise(set = case_when(
    any(set == "Member substantive role and society purpose related") ~ "Member substantive role and society purpose related",
    any(set == "Member substantive role") ~ "Member substantive role",
    T ~ "Member linked"
  ), method = sql("GROUP_CONCAT(method ORDER BY method SEPARATOR '&')"), .groups = "drop")

fbs_records_a <- fbs_records_a %>%
  union_all(fbs_records_a %>%
    filter(set == "Member substantive role and society purpose related") %>%
    mutate(set = "Member substantive role")) %>%
  union_all(fbs_records_a %>%
    filter(set != "Member linked") %>%
    mutate(set = "Member linked")) %>%
  anti_join(vd17_record_types_a %>% filter(record_type == "Unified multi-part publication") %>% inner_join(vd17_id_a)) %>%
  compute_a(unique_indexes = list(c("vd17_id", "set"))) #

fbs_records_a <- fbs_records_a %>%
  union_all(fbs_records_a %>%
    inner_join(vd17_id_a) %>%
    inner_join(fbs_links_of_interest_a %>% select(-method), join_by(record_number)) %>%
    inner_join(fbs_metadata_a) %>%
    inner_join(vd17_normalized_years_a, join_by(record_number)) %>%
    filter(normalized_year >= Estimated_admission_year, normalized_year <= Estimated_DOD) %>%
    distinct(vd17_id, set, method) %>%
    mutate(set = str_c("Active ", str_to_lower(set)))) %>%
  compute_a(name = "fbs_records_a", temporary = FALSE, overwrite = TRUE, unique_indexes = list(c("vd17_id", "set")))

fbs_records_c <- fbs_records_a %>%
  compute_c(name = "fbs_records_c", temporary = FALSE, overwrite = TRUE)
```
